const {test,expect}=require('../lib/fixtures');
const {rows,literal,sql}=require('../lib/db');
const {createCustomer,openForm,choose,submit,closeForm,finalize,routes}=require('../lib/ui');
const company=()=>rows('SELECT billing_entity_id,name FROM billing_entities WHERE account_id=9001 AND is_default')[0];
async function capture(page,info,name){const path=info.outputPath(name+'.png');await page.screenshot({path,fullPage:true});await info.attach(name,{path,contentType:'image/png'});}
async function addBusiness(page,prefix){
 await page.goto('/settings/entities/new');const name=prefix+' Advisory';
 await page.getByLabel('Business name',{exact:false}).fill(name);await page.getByLabel('Legal name',{exact:false}).fill(name+' LLC');const code='H'+Array.from(require('crypto').randomBytes(6),b=>String.fromCharCode(65+b%26)).join('');await page.getByLabel('Invoice prefix',{exact:false}).fill(code);await page.getByLabel('Reason for change').fill('Separate synthetic business');
 const response=page.waitForResponse(r=>r.url().endsWith('/billing-entities') && r.request().method()==='POST');await page.getByRole('button',{name:'Save business'}).dblclick();expect((await response).status()).toBe(200);await expect(page.getByText('Business saved.')).toBeVisible();
 const found=rows(`SELECT * FROM billing_entities WHERE account_id=9001 AND name=${literal(name)}`);expect(found).toHaveLength(1);return found[0];
}
test('a delayed business list keeps the entered draft and saves it exactly once',async({page,prefix})=>{
 let release,arrived,held=false;const ready=new Promise(resolve=>{arrived=resolve;}),gate=new Promise(resolve=>{release=resolve;});
 await page.route('**/billing-entities',async route=>{if(route.request().method()==='GET' && !held){held=true;arrived();await gate;}await route.fallback();});
 const name=prefix+' Delayed business',reason='Preserve the draft while choices load',code='D'+Array.from(require('crypto').randomBytes(6),b=>String.fromCharCode(65+b%26)).join('');
 try{
  await page.goto('/settings/entities/new');await ready;
  await page.getByLabel('Business name',{exact:false}).fill(name);await page.getByLabel('Legal name',{exact:false}).fill(name+' LLC');await page.getByLabel('Invoice prefix',{exact:false}).fill(code);await page.getByLabel('Reason for change').fill(reason);
  expect(rows(`SELECT * FROM billing_entities WHERE account_id=9001 AND name=${literal(name)}`)).toHaveLength(0);
  const loaded=page.waitForResponse(r=>r.url().endsWith('/billing-entities') && r.request().method()==='GET');release();expect((await loaded).status()).toBe(200);
  // Wait for React to render the completed list response before checking the draft.
  await page.waitForLoadState('networkidle');await expect(page.getByLabel('Business name',{exact:false})).toHaveValue(name);await expect(page.getByLabel('Legal name',{exact:false})).toHaveValue(name+' LLC');await expect(page.getByLabel('Invoice prefix',{exact:false})).toHaveValue(code);await expect(page.getByLabel('Reason for change')).toHaveValue(reason);
  const saved=page.waitForResponse(r=>r.url().endsWith('/billing-entities') && r.request().method()==='POST');await page.getByRole('button',{name:'Save business'}).dblclick();expect((await saved).status()).toBe(200);await expect(page.getByText('Business saved.')).toBeVisible();expect(rows(`SELECT * FROM billing_entities WHERE account_id=9001 AND name=${literal(name)}`)).toHaveLength(1);
 // This test owns a fresh context. Keep its routing chain installed until
 // context disposal: removing it while the save refetch/idle chunks arrive
 // can re-dispatch an already handled request to the shared safety guard.
 }finally{release();}
 await page.waitForLoadState('networkidle');
});
async function work(page,c,entityId,amount){
 let d=await openForm(page,routes.jobs,'Add New Customer Job');await choose(page,d,'Select Customer',c.name);await d.getByRole('combobox',{name:/Billing business/}).selectOption(String(entityId));await choose(page,d,'Filter Job Types By Category','Tax Compliance');await choose(page,d,'Type Of Job','1040 Individual Return');await submit(page,d,'/jobs/createJob/');await closeForm(page);
 d=await openForm(page,routes.transactions,'New Charge');await choose(page,d,'Select Customer',c.name);await d.getByRole('combobox',{name:/Billing business/}).selectOption(String(entityId));await choose(page,d,'Select Job','1040 Individual Return');await choose(page,d,'Select Team Member','Eliza Smith');await choose(page,d,'General Work Description','Tax Return Preparation');await d.getByLabel('Work Completed On Job').fill(c.prefix+' entity work');await d.getByLabel('Quantity',{exact:true}).fill('1');await d.getByLabel('Unit Cost').fill(String(amount));await submit(page,d,'/transactions/createTransaction/');await closeForm(page);
}
test('admin manages letterhead, enters two businesses and finalizes separate statements; AR filters stay separate',async({page,prefix},testInfo)=>{
 const b=await addBusiness(page,prefix),a=company();expect(b.invoice_prefix).not.toBe('INV');await expect(page.getByText('Letterhead preview')).toBeVisible();await capture(page,testInfo,'billing-business-settings');
 const c=await createCustomer(page,prefix);await work(page,c,a.billing_entity_id,22.5);await work(page,c,b.billing_entity_id,40);
 const workRows=rows(`SELECT billing_entity_id,total_transaction FROM customer_transactions WHERE account_id=9001 AND customer_id=${c.id} ORDER BY transaction_id`);expect(workRows.map(r=>[r.billing_entity_id,Number(r.total_transaction)])).toEqual([[a.billing_entity_id,22.5],[b.billing_entity_id,40]]);
 await finalize(page,c,{entityId:a.billing_entity_id,expectedTotal:'22.50',testInfo});await finalize(page,c,{entityId:b.billing_entity_id,expectedTotal:'40.00',testInfo});
 const invoices=rows(`SELECT billing_entity_id,invoice_number,total_amount_due FROM customer_invoices WHERE account_id=9001 AND customer_id=${c.id} AND parent_invoice_id IS NULL ORDER BY customer_invoice_id`);expect(invoices).toHaveLength(2);expect(invoices[1].invoice_number).toMatch(new RegExp('^'+b.invoice_prefix+'-'));expect(invoices.map(i=>Number(i.total_amount_due))).toEqual([22.5,40]);
 await page.goto('/receivables/aging');await page.getByPlaceholder('Search by business name, customer name, display name, or ID').fill(c.prefix);await page.getByRole('button',{name:'Search',exact:true}).click();
 for(const [entity,amount] of [[a,'$22.50'],[b,'$40.00']]){await page.getByRole('combobox',{name:/Billing business/}).selectOption(String(entity.billing_entity_id));const r=page.getByRole('row').filter({hasText:c.name});await expect(r).toHaveCount(1);await expect(r).toContainText(entity.name);await expect(r).toContainText(amount);}
 await capture(page,testInfo,'ar-business-filter');await page.goto(`/settings/entities/${b.billing_entity_id}`);await page.getByLabel('Active business',{exact:true}).uncheck();await page.getByLabel('Reason for change').fill('Attempt to deactivate open balances');const res=page.waitForResponse(r=>r.request().method()==='PATCH');await page.getByRole('button',{name:'Save business'}).click();expect((await res).status()).toBe(409);await expect(page.getByText(/open balances or held funds/)).toBeVisible();expect(rows(`SELECT active FROM billing_entities WHERE account_id=9001 AND billing_entity_id=${b.billing_entity_id}`)[0].active).toBe(true);
});
test('wrong business clears selected job and invalid invoice choices; settings, mapping and opening screens remain reachable',async({page,prefix})=>{
 const b=await addBusiness(page,prefix),a=company(),c=await createCustomer(page,prefix);await work(page,c,a.billing_entity_id,10);
 const d=await openForm(page,routes.transactions,'New Charge');await choose(page,d,'Select Customer',c.name);await d.getByRole('combobox',{name:/Billing business/}).selectOption(String(a.billing_entity_id));await choose(page,d,'Select Job','1040 Individual Return');await d.getByRole('combobox',{name:/Billing business/}).selectOption(String(b.billing_entity_id));await expect(d.getByRole('combobox',{name:'Select Job',exact:true})).toHaveValue('');await closeForm(page);
 await page.goto('/work/review/entities');await expect(page.getByRole('heading',{name:'Business assignments needing review'})).toBeVisible();await page.goto('/settings/entities/cutover');await expect(page.getByRole('heading',{name:'Assign legacy opening balances'})).toBeVisible();await expect(page.getByRole('button',{name:'Apply reviewed opening balances'})).toBeDisabled();
 await page.goto('/payments/transfers');await expect(page.getByLabel('Reason for transfer')).toBeVisible();await expect(page.getByRole('button',{name:'Transfer credit'})).toBeDisabled();
});
test.describe('employee company permissions',()=>{test.use({identity:'employee'});test('readable transfer history has no posting control and settings are protected',async({page})=>{await page.goto('/payments/transfers');await expect(page.getByText(/Only admins can transfer credit/)).toBeVisible();await expect(page.getByRole('button',{name:'Transfer credit'})).toHaveCount(0);await page.goto('/settings/entities');await expect(page.getByRole('heading',{name:'Unauthorized'})).toBeVisible();});});

test('admin transfers unused credit once, with a reason and no new receipt',async({page,prefix},testInfo)=>{
 const b=await addBusiness(page,prefix),a=company(),c=await createCustomer(page,prefix);
 const d=await openForm(page,routes.retainers,'New Retainer');await choose(page,d,'Select Customer',c.name);await d.getByRole('combobox',{name:/Billing business/}).selectOption(String(a.billing_entity_id));await choose(page,d,'Select Team Member','Admin Person');await choose(page,d,'Form Of Payment','Cash');await d.getByLabel('Payment Amount',{exact:true}).fill('25');await d.getByLabel('Label of Retainer Or Payment').fill(prefix);await choose(page,d,'Type of Hold','Retainer');await submit(page,d,'/retainers/create');await closeForm(page);
 await page.goto('/payments/transfers');await page.getByRole('combobox',{name:'Client',exact:true}).selectOption(String(c.id));await page.getByRole('combobox',{name:'From business',exact:true}).selectOption(String(a.billing_entity_id));await page.getByRole('combobox',{name:'To business',exact:true}).selectOption(String(b.billing_entity_id));await page.getByRole('combobox',{name:'Available credit'}).selectOption({label:prefix+' — $25.00 available'});
 await page.getByLabel('Amount to transfer').fill('26');await page.getByLabel('Reason for transfer').fill('Move funds to advisory work');expect(await page.getByLabel('Amount to transfer').evaluate(el=>el.checkValidity())).toBe(false);await page.getByRole('button',{name:'Transfer credit',exact:true}).click();expect(rows(`SELECT * FROM billing_credit_transfers WHERE account_id=9001 AND customer_id=${c.id}`)).toHaveLength(0);
 await page.getByLabel('Amount to transfer').fill('10');const posted=page.waitForResponse(r=>r.url().endsWith('/billing-entities/transfers') && r.request().method()==='POST');await page.getByRole('button',{name:'Transfer credit',exact:true}).dblclick();expect((await posted).status()).toBe(200);await expect(page.getByText(/Move funds to advisory work/)).toBeVisible();
 const transfers=rows(`SELECT * FROM billing_credit_transfers WHERE account_id=9001 AND customer_id=${c.id}`);expect(transfers).toHaveLength(1);expect(Number(transfers[0].amount)).toBe(10);expect(rows(`SELECT * FROM customer_payments WHERE account_id=9001 AND customer_id=${c.id}`)).toHaveLength(0);
 const balances=rows(`SELECT billing_entity_id,current_amount FROM customer_retainers_and_prepayments r WHERE account_id=9001 AND customer_id=${c.id} AND NOT EXISTS(SELECT 1 FROM customer_retainers_and_prepayments ch WHERE ch.account_id=r.account_id AND ch.parent_retainer_id=r.retainer_id) ORDER BY retainer_id`).map(r=>Number(r.current_amount));expect(balances).toEqual([-15,-10]);await capture(page,testInfo,'credit-transfer');
});
test('an unknown tracker business needs an explicit assignment and reason before leaving review',async({page,prefix})=>{
 const c=await createCustomer(page,prefix),b=await addBusiness(page,prefix);const [row]=JSON.parse(sql(`WITH cfg AS MATERIALIZED (SELECT set_config('app.billing_entity_id','',true)), entry AS (INSERT INTO timesheet_entries(account_id,user_id,timesheet_name,time_tracker_start_date,time_tracker_end_date,date,entity,company_name,notes,duration,is_processed,is_deleted) SELECT 9001,90011,${literal(prefix+'.xlsx')},CURRENT_DATE-7,CURRENT_DATE,CURRENT_DATE,${literal(prefix+' Advsory typo')},${literal(c.name)},${literal(prefix+' review work')},6,false,false FROM cfg RETURNING *) INSERT INTO billing_entity_reviews(account_id,customer_id,table_name,record_id,raw_entity,candidate_ids,source_sha256,reason_code) SELECT account_id,${c.id},'timesheet_entries',timesheet_entry_id,entity,'{}',repeat('0',64),'entity_unknown' FROM entry RETURNING json_build_array(json_build_object('review_id',review_id,'record_id',record_id))`));
 await page.goto('/work/review/entities');let card=page.locator('.MuiPaper-root').filter({hasText:prefix+' review work'});await page.getByRole('heading',{name:'Business assignments needing review'}).waitFor();await expect(async()=>{if(!await card.count() && await page.getByRole('button',{name:'Next',exact:true}).isEnabled())await page.getByRole('button',{name:'Next',exact:true}).click();await expect(card).toBeVisible({timeout:1000});}).toPass({timeout:15000});
 await expect(card).toBeVisible();await expect(card).toContainText('Client '+c.name);await expect(card).not.toContainText('Client '+c.id);await expect(card.getByRole('button',{name:'Save assignment'})).toBeDisabled();await card.getByRole('combobox',{name:'Assign billing business'}).selectOption(String(b.billing_entity_id));await expect(card.getByRole('button',{name:'Save assignment'})).toBeDisabled();await card.getByLabel('Reason for assignment').fill('Verified advisory source');const posted=page.waitForResponse(r=>r.url().includes(`/review/${row.review_id}/resolve`));await card.getByRole('button',{name:'Save assignment'}).dblclick();expect((await posted).status()).toBe(200);await expect(card).toHaveCount(0);expect(rows(`SELECT billing_entity_id FROM timesheet_entries WHERE account_id=9001 AND timesheet_entry_id=${row.record_id}`)[0].billing_entity_id).toBe(b.billing_entity_id);expect(rows(`SELECT * FROM billing_entity_resolutions WHERE account_id=9001 AND review_id=${row.review_id}`)).toHaveLength(1);
});
test('opening allocation validates the total and saves separate shares without editing the legacy row',async({page,prefix})=>{
 const b=await addBusiness(page,prefix),a=company(),c=await createCustomer(page,prefix);
 let source=JSON.parse(sql(`INSERT INTO customer_invoices(account_id,customer_id,customer_info_id,billing_entity_id,invoice_number,invoice_date,due_date,beginning_balance,total_payments,total_charges,total_write_offs,total_retainers,total_amount_due,remaining_balance_on_invoice,is_invoice_paid_in_full,created_by_user_id) VALUES(9001,${c.id},(SELECT customer_info_id FROM customer_information WHERE account_id=9001 AND customer_id=${c.id} LIMIT 1),${a.billing_entity_id},${literal(prefix+'-LEGACY')},CURRENT_DATE-60,CURRENT_DATE-45,0,0,90,0,0,90,90,false,90013) RETURNING row_to_json(customer_invoices)`));
 const co=JSON.parse(sql(`INSERT INTO billing_cutovers(account_id,source,manifest,manifest_sha256) VALUES(9001,${literal(prefix)},'{"synthetic":true}',repeat('0',64)) RETURNING json_build_object('cutover_id',cutover_id)`));
 sql(`BEGIN;SET LOCAL session_replication_role=replica;UPDATE customer_invoices SET billing_entity_id=NULL WHERE account_id=9001 AND customer_invoice_id=${source.customer_invoice_id};INSERT INTO legacy_financial_entity_attributions(account_id,customer_id,table_name,record_id,billing_entity_id,cutover_id,source_sha256,basis) VALUES(9001,${c.id},'customer_invoices',${source.customer_invoice_id},${a.billing_entity_id},${co.cutover_id},repeat('0',64),'Synthetic browser legacy source');COMMIT;`);
 source=rows(`SELECT * FROM customer_invoices WHERE account_id=9001 AND customer_invoice_id=${source.customer_invoice_id}`)[0];
 sql(`INSERT INTO billing_cutover_positions(account_id,customer_id,billing_entity_id,cutover_id,source_root_id,source_snapshot_id,opening_amount,source_sha256,basis) SELECT account_id,customer_id,${a.billing_entity_id},${co.cutover_id},customer_invoice_id,customer_invoice_id,90,encode(sha256(convert_to((to_jsonb(i)-'billing_entity_id')::text,'UTF8')),'hex'),'Synthetic browser opening' FROM customer_invoices i WHERE account_id=9001 AND customer_invoice_id=${source.customer_invoice_id}`);
 await page.goto('/settings/entities/cutover');const card=page.locator('.MuiPaper-root').filter({hasText:c.name});await card.getByRole('checkbox').check();await card.getByRole('button',{name:'Split with another business'}).click();await card.getByLabel('Opening share').nth(0).fill('60');await card.getByLabel('Opening share').nth(1).fill('29');await card.getByLabel('Business',{exact:true}).nth(1).selectOption(String(b.billing_entity_id));await page.getByLabel('Reason for opening allocation').fill('Reviewed legacy tax/advisory split');await expect(page.getByRole('button',{name:'Apply reviewed opening balances'})).toBeDisabled();await card.getByLabel('Opening share').nth(1).fill('30');const posted=page.waitForResponse(r=>r.url().endsWith('/billing-entities/cutover') && r.request().method()==='POST');await page.getByRole('button',{name:'Apply reviewed opening balances'}).dblclick();expect((await posted).status()).toBe(200);await expect(page.getByText('Opening balances assigned. Original statements remain unchanged.')).toBeVisible();expect(rows(`SELECT opening_amount FROM billing_cutover_allocations WHERE account_id=9001 AND customer_id=${c.id} ORDER BY allocation_id`).map(r=>Number(r.opening_amount))).toEqual([60,30]);expect(rows(`SELECT * FROM customer_invoices WHERE account_id=9001 AND customer_invoice_id=${source.customer_invoice_id}`)[0]).toEqual(source);
});
