const {test,expect}=require('../lib/fixtures');
const {billedCustomer,createCustomer,finalize,routes}=require('../lib/ui');
const {rows,sql,literal}=require('../lib/db');
const {saveDownload}=require('../lib/download');
const {randomUUID}=require('crypto');
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const entity=()=>rows('SELECT billing_entity_id FROM billing_entities WHERE account_id=9001 AND is_default')[0].billing_entity_id;
async function api(page,path,body){
 if(!/^\/(invoices|credits|credit-memos|payments\/receipts|payments\/open-obligations)(\/|\?|$)/.test(path))throw Error('Unexpected H3 fixture API');
 const r=body===undefined?await page.request.get('http://localhost:8003'+path):await page.request.post('http://localhost:8003'+path,{data:body,headers:{'Idempotency-Key':randomUUID()}});
 expect(r.ok(),await r.text()).toBeTruthy();return r.json();
}
const state=c=>rows(`SELECT 'invoice' AS kind,customer_invoice_id::text AS id,row_to_json(i)::text AS data FROM customer_invoices i WHERE account_id=9001 AND customer_id=${c.id} UNION ALL SELECT 'audit',event_id::text,row_to_json(e)::text FROM audit_events e WHERE account_id=9001 AND customer_id=${c.id} ORDER BY kind,id`);
async function openInvoice(page,i){await page.goto(routes.invoices);await page.getByPlaceholder('Search invoices').fill(i.invoice_number);await page.locator(`[role="row"][data-id="${i.customer_invoice_id}"]`).click();await expect(page.getByText(/Original new charges/)).toBeVisible();}
async function fixture(page,prefix){const c=await billedCustomer(page,prefix);await finalize(page,c);const [i]=rows(`SELECT * FROM customer_invoices WHERE account_id=9001 AND customer_id=${c.id} AND parent_invoice_id IS NULL`);await openInvoice(page,i);return {...c,entityId:entity(),i};}
async function memoForm(page,amount='10'){await page.getByRole('button',{name:'Credit memo',exact:true}).click();await page.getByLabel('Credit memo amount').fill(amount);await page.getByLabel('Correction reason').fill('Correct duplicated professional fee');}
async function voidForm(page){await page.getByRole('button',{name:'Void and rebill',exact:true}).click();await page.getByLabel('Corrected charge 1 description').fill('Corrected professional services');await page.getByLabel('Corrected charge 1 amount').fill('30');await page.getByLabel('Correction reason').fill('Original used an incorrect rate');}
async function commit(page,mode,{double=false}={}){
 await page.getByRole('button',{name:'Review correction',exact:true}).click();
 const r=page.waitForResponse(r=>r.url().endsWith('/'+mode) && r.request().method()==='POST');
 const b=page.getByRole('button',{name:'Finalize correction',exact:true});if(double)await b.dblclick();else await b.click();return r;
}
async function pay(page,c,amount){const s=await api(page,`/payments/open-obligations?customerId=${c.id}&entityId=${c.entityId}`);let left=amount;return api(page,'/payments/receipts',{customerId:c.id,entityId:c.entityId,amount,date:today(),method:'cash',reference:'',allocations:s.obligations.flatMap(o=>{const n=Math.min(left,o.openCents/100);left-=n;return n?[{obligationId:o.obligation_id,amount:n}]:[];}),ledgerFingerprint:s.ledgerFingerprint});}
async function creditFixture(page,prefix){const c=await createCustomer(page,prefix);c.entityId=entity();const p=await pay(page,c,350);c.creditId=p.credit.credit_id;return c;}
async function refundForm(page,c){await page.goto('/payments/credits');await page.getByLabel('Credit client').selectOption(String(c.id));await page.getByLabel('Credit business').selectOption(String(c.entityId));await page.getByRole('button',{name:`Refund credit #${c.creditId}`,exact:true}).click();await page.getByLabel('Refund amount').fill('350');await page.getByLabel('Refund method').selectOption('cash');await page.getByLabel('Refund reason').fill('Return unused client funds');}
async function refundSave(page){await page.getByRole('button',{name:'Review refund',exact:true}).click();const r=page.waitForResponse(r=>r.url().endsWith(`/refunds`) && r.request().method()==='POST');await page.getByRole('button',{name:'Record refund',exact:true}).dblclick();return r;}
async function download(page,button,info,label){const promise=page.waitForEvent('download');await button.click();const d=await promise;expect(await d.failure()).toBeNull();const f=await saveDownload(d);if(info)await info.attach(label,{path:f,contentType:d.suggestedFilename().endsWith('.pdf')?'application/pdf':'application/zip'});return f;}

test('credit memo reduces debt, preserves original PDF and is reversible only by a compensating document',async({page,prefix},info)=>{
 const c=await fixture(page,prefix),original=rows(`SELECT row_to_json(i) AS data FROM customer_invoices i WHERE account_id=9001 AND customer_invoice_id=${c.i.customer_invoice_id}`);
 await memoForm(page);expect((await commit(page,'credit-memos',{double:true})).status()).toBe(200);await expect(page.getByText('Credit memo finalized and locked. Original invoice preserved.')).toBeVisible();
 const [m]=rows(`SELECT * FROM credit_memos WHERE account_id=9001 AND customer_id=${c.id}`);expect(Number(m.amount)).toBe(10);expect(rows(`SELECT row_to_json(i) AS data FROM customer_invoices i WHERE account_id=9001 AND customer_invoice_id=${c.i.customer_invoice_id}`)).toEqual(original);
 await expect(page.getByText(/Open debt \$12.50/)).toBeVisible();await download(page,page.getByRole('button',{name:'Download '+m.number,exact:true}),info,'credit-memo.pdf');await download(page,page.getByRole('button',{name:/Reprint original/}),info,'original.zip');
 await page.goto('/receivables/aging');await page.getByPlaceholder('Search by business name, customer name, display name, or ID').fill(prefix);await page.getByRole('button',{name:'Search',exact:true}).click();await expect(page.getByRole('row').filter({hasText:c.name})).toContainText('$12.50');
 await page.goto('/billing/credit-memos');await page.getByRole('button',{name:'Reverse memo '+m.number,exact:true}).click();await expect(page.getByRole('button',{name:'Confirm memo reversal'})).toBeDisabled();await page.getByLabel('Memo reversal reason').fill('Courtesy decision entered twice');await page.getByRole('button',{name:'Confirm memo reversal'}).click();await expect(page.getByText('Memo reversed with a linked compensating document.')).toBeVisible();await download(page,page.getByRole('button',{name:'Download reversal of '+m.number,exact:true}),info,'memo-reversal.pdf');expect((await api(page,`/payments/open-obligations?customerId=${c.id}&entityId=${c.entityId}`)).billedCents).toBe(2250);
 await page.screenshot({path:info.outputPath('credit-memo-register.png'),fullPage:true});
});
for(const [name,amount,reason] of [['above original charges','23','Correct fee'],['fractional cents','1.001','Correct fee'],['missing reason','10','']])test(`memo blocks ${name} before posting`,async({page,prefix})=>{const c=await fixture(page,prefix),before=state(c);await memoForm(page,amount);await page.getByLabel('Correction reason').fill(reason);await expect(page.getByRole('button',{name:'Review correction',exact:true})).toBeDisabled();expect(state(c)).toEqual(before);});
test('memo above open amount requires explicit confirmation of new credit',async({page,prefix})=>{const c=await fixture(page,prefix);await pay(page,c,22.50);await openInvoice(page,c.i);await memoForm(page);await expect(page.getByRole('button',{name:'Review correction',exact:true})).toBeDisabled();await page.getByLabel('Confirm $10.00 becomes client credit').check();expect((await commit(page,'credit-memos')).status()).toBe(200);expect((await api(page,`/payments/open-obligations?customerId=${c.id}&entityId=${c.entityId}`)).billedCents).toBe(-1000);});
for(const mode of ['credit-memos','void-rebill'])test(`${mode} refuses a stale screen without losing the correction`,async({page,prefix})=>{
 const c=await fixture(page,prefix);if(mode==='credit-memos')await memoForm(page);else await voidForm(page);await page.getByRole('button',{name:'Review correction',exact:true}).click();await expect(page.getByRole('button',{name:'Finalize correction'})).toBeVisible();await pay(page,c,1);const before=state(c),r=page.waitForResponse(r=>r.url().endsWith('/'+mode) && r.request().method()==='POST');await page.getByRole('button',{name:'Finalize correction'}).click();expect((await r).status()).toBe(409);await expect(page.getByRole('button',{name:'Refresh correction'})).toBeVisible();expect(state(c)).toEqual(before);await expect(page.getByLabel('Correction reason')).not.toBeEmpty();await page.getByRole('button',{name:'Refresh correction'}).click();await expect(page.getByRole('button',{name:'Finalize correction'})).toHaveCount(0);expect((await commit(page,mode)).status()).toBe(200);
});
for(const [field,value] of [['entityId',2147483646],['invoice',2147483646]])test(`memo tampered wrong ${field} is rejected with no changes`,async({page,prefix})=>{
 const c=await fixture(page,prefix),before=state(c);await memoForm(page);await page.route('**/invoices/*/credit-memos',route=>field==='invoice'?route.continue({url:'http://localhost:8003/invoices/2147483646/credit-memos'}):route.continue({postData:JSON.stringify({...route.request().postDataJSON(),[field]:value})}));expect((await commit(page,'credit-memos')).status()).toBe(404);expect(state(c)).toEqual(before);await expect(page.getByRole('button',{name:'Refresh correction'})).toBeVisible();
});
test('void/rebill preserves original and new PDFs, uses a new number and cannot be repeated',async({page,prefix},info)=>{
 const c=await fixture(page,prefix);await pay(page,c,22.50);await openInvoice(page,c.i);await voidForm(page);await page.getByLabel('Correction reason').fill('');await expect(page.getByRole('button',{name:'Review correction'})).toBeDisabled();await page.getByLabel('Correction reason').fill('Correct rate');await page.getByLabel('Corrected charge 1 amount').fill('-1');await expect(page.getByRole('button',{name:'Review correction'})).toBeDisabled();await page.getByLabel('Corrected charge 1 amount').fill('30');
 expect((await commit(page,'void-rebill',{double:true})).status()).toBe(200);await expect(page.getByText(/Original — void/)).toBeVisible();await expect(page.getByRole('button',{name:'Void and rebill',exact:true})).toHaveCount(0);expect(rows(`SELECT * FROM invoice_voids WHERE account_id=9001 AND customer_id=${c.id}`)).toHaveLength(1);
 await download(page,page.getByRole('button',{name:'Download void document'}),info,'void.pdf');await download(page,page.getByRole('button',{name:/Reprint original/}),info,'void-original.zip');
 const [link]=rows(`SELECT * FROM rebill_links WHERE account_id=9001 AND customer_id=${c.id}`);await page.getByRole('link',{name:'Open corrected invoice'}).click();await expect(page.getByText(/Original new charges \$30.00/)).toBeVisible();await download(page,page.getByRole('button',{name:/Reprint original/}),info,'corrected-invoice.zip');expect(link.original_invoice_id).not.toBe(link.replacement_invoice_id);expect((await api(page,`/payments/open-obligations?customerId=${c.id}&entityId=${c.entityId}`)).billedCents).toBe(750);await page.getByRole('link',{name:'Open original invoice'}).click();await expect(page.getByText(/Original — void/)).toBeVisible();await page.screenshot({path:info.outputPath('void-original-history.png'),fullPage:true});
});
test('refund of $350 credit records money returned once with no AR effect',async({page,prefix},info)=>{
 const c=await creditFixture(page,prefix);await refundForm(page,c);await page.getByLabel('Refund amount').fill('351');await expect(page.getByText('Refund exceeds available credit.')).toBeVisible();await expect(page.getByRole('button',{name:'Review refund'})).toBeDisabled();await page.getByLabel('Refund amount').fill('350');await page.getByLabel('Refund reason').fill('');await expect(page.getByRole('button',{name:'Review refund'})).toBeDisabled();await page.getByLabel('Refund reason').fill('Return unused funds');expect((await refundSave(page)).status()).toBe(200);await expect(page.getByText(/Remaining credit \$0.00/)).toBeVisible();const [r]=rows(`SELECT * FROM client_refunds WHERE account_id=9001 AND customer_id=${c.id}`);expect(Number(r.amount)).toBe(350);const s=await api(page,`/payments/open-obligations?customerId=${c.id}&entityId=${c.entityId}`);expect(s.billedCents).toBe(0);expect(s.credits.reduce((n,c)=>n+c.availableCents,0)).toBe(0);expect(rows(`SELECT * FROM customer_payments WHERE account_id=9001 AND customer_id=${c.id}`)).toHaveLength(0);await page.getByRole('main').getByRole('link',{name:'Refund history',exact:true}).click();await download(page,page.getByRole('button',{name:'Download refund #'+r.refund_id,exact:true}),info,'refund.pdf');await page.screenshot({path:info.outputPath('refund-history.png'),fullPage:true});
});
for(const wrong of ['stale','entity','credit'])test(`refund rejects ${wrong} data and retains the form`,async({page,prefix})=>{
 const c=await creditFixture(page,prefix);await refundForm(page,c);if(wrong==='stale'){const s=await api(page,`/credits?customerId=${c.id}&entityId=${c.entityId}`);await api(page,`/credits/${c.creditId}/refunds`,{entityId:c.entityId,amount:1,date:today(),method:'cash',reason:'Concurrent refund',ledgerFingerprint:s.ledgerFingerprint});}else await page.route('**/credits/*/refunds',route=>wrong==='credit'?route.continue({url:'http://localhost:8003/credits/2147483646/refunds'}):route.continue({postData:JSON.stringify({...route.request().postDataJSON(),entityId:2147483646})}));const before=state(c);expect((await refundSave(page)).status()).toBe(wrong==='stale'?409:404);await expect(page.getByLabel('Refund amount')).toHaveValue('350');await expect(page.getByRole('button',{name:'Refresh available credit'})).toBeVisible();expect(state(c)).toEqual(before);
});
for(const role of ['manager','employee','SUPER ADMIN'])test(`${role} correction controls match backend authority`,async({page,prefix})=>{
 const c=await fixture(page,prefix),url=page.url();const createdRetainer=await page.request.post('http://localhost:8003/retainers/createRetainer/9001/90013',{data:{retainer:{customerID:c.id,entityId:c.entityId,unitCost:25,typeOfHold:'Retainer',displayName:prefix}}});expect(createdRetainer.ok()).toBeTruthy();expect((await createdRetainer.json()).status).toBe(200);const work=rows(`SELECT transaction_id FROM customer_transactions WHERE account_id=9001 AND customer_id=${c.id}`)[0];const flagged=await page.request.post('http://localhost:8003/duplicates/9001/90013',{data:{kind:'transaction',recordId:work.transaction_id,reason:'Permission review'}});expect(flagged.ok()).toBeTruthy();const flag=(await flagged.json()).duplicate;const old=rows('SELECT access_level FROM users WHERE account_id=9001 AND user_id=90013')[0].access_level;
 try{sql(`UPDATE users SET access_level=${literal(role)} WHERE account_id=9001 AND user_id=90013`);await page.evaluate(v=>sessionStorage.setItem('accessLevel',v),role);await page.goto(url);
  if(role==='SUPER ADMIN'){await memoForm(page);expect((await commit(page,'credit-memos')).status()).toBe(200);await expect(page.getByText(/Credit memo finalized/)).toBeVisible();}
  else{const before=state(c);for(const button of ['Credit memo','Void and rebill','Flag exception','Reverse selected payments','Issue revision for reprint / resend','Roll into next invoice'])await expect(page.getByRole('button',{name:button,exact:true})).toHaveCount(0);if(role==='manager')await expect(page.getByText(/Only admins may issue credit memos/)).toBeVisible();else await expect(page.getByText('You are not authorized to access this page.')).toBeVisible();await page.goto(routes.writeoffs);await expect(page.getByRole('button',{name:'New Write Off',exact:true})).toHaveCount(0);await page.goto('/payments/credits');await expect(page.getByRole('button',{name:/Refund credit #/})).toHaveCount(0);await page.goto(`/clients/${c.id}/credits`);await expect(page.getByRole('button',{name:'Review event',exact:true})).toHaveCount(0);if(role==='manager')await expect(page.getByText('Only admins may refund or adjust retainers.')).toBeVisible();await page.goto('/work/duplicates?duplicateId='+flag.duplicate_id);for(const name of ['Remove duplicate','Confirm removal'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);expect(state(c)).toEqual(before);}
 }finally{sql(`UPDATE users SET access_level=${literal(old)} WHERE account_id=9001 AND user_id=90013`);}
});
