const {test,expect}=require('../lib/fixtures');
const {rows,literal,sql}=require('../lib/db');
const {createCustomer,createJob,openForm,choose,submit,closeForm,finalize,routes}=require('../lib/ui');
const {randomUUID}=require('crypto');
const entity=()=>rows('SELECT billing_entity_id FROM billing_entities WHERE account_id=9001 AND is_default')[0].billing_entity_id;
async function fixture(page,prefix){
 const c=await createCustomer(page,prefix),e=entity();
 for(const [i,charge,begin,age]of [[1,300,0,75],[2,450,300,45],[3,400,750,15]])sql(`INSERT INTO customer_invoices(account_id,customer_id,customer_info_id,billing_entity_id,invoice_number,invoice_date,due_date,beginning_balance,total_payments,total_charges,total_write_offs,total_retainers,total_amount_due,remaining_balance_on_invoice,is_invoice_paid_in_full,created_by_user_id,created_at) VALUES(9001,${c.id},(SELECT customer_info_id FROM customer_information WHERE account_id=9001 AND customer_id=${c.id} LIMIT 1),${e},${literal(prefix+'-INV'+i)},CURRENT_DATE-${age},CURRENT_DATE-${age}+15,${begin},0,${charge},0,0,${begin+charge},${begin+charge},false,90013,(clock_timestamp() AT TIME ZONE 'UTC')-interval '${age} days')`);
 return {...c,entityId:e};
}
async function start(page,c,amount='1000'){
 await page.goto('/payments/receive');await page.getByLabel('Client',{exact:true}).selectOption(String(c.id));await page.getByLabel(/Billing business/).selectOption(String(c.entityId));
 await expect(page.getByLabel('Apply to '+c.prefix+'-INV1')).toBeVisible();await page.getByLabel('Amount received',{exact:true}).fill(amount);await page.getByLabel('Check / payment reference').fill(c.prefix+'-CHECK');
}
async function save(page){await page.getByRole('button',{name:'Review payment',exact:true}).click();const res=page.waitForResponse(r=>r.url().endsWith('/payments/receipts') && r.request().method()==='POST');await page.getByRole('button',{name:'Record payment',exact:true}).dblclick();return res;}
const state=c=>rows(`SELECT 'receipt' AS kind,receipt_id::text AS id,row_to_json(r)::text AS data FROM payment_receipts r WHERE account_id=9001 AND customer_id=${c.id} UNION ALL SELECT 'application',application_id::text,row_to_json(a)::text FROM ar_applications a WHERE account_id=9001 AND customer_id=${c.id} UNION ALL SELECT 'invoice',customer_invoice_id::text,row_to_json(i)::text FROM customer_invoices i WHERE account_id=9001 AND customer_id=${c.id} UNION ALL SELECT 'audit',event_id::text,row_to_json(e)::text FROM audit_events e WHERE account_id=9001 AND customer_id=${c.id} ORDER BY kind,id`);
async function api(page,path,body){if(!/^\/payments\/(receipts|open-obligations)/.test(path))throw Error('Unexpected receipt fixture API');const r=body===undefined?await page.request.get('http://localhost:8003'+path):await page.request.post('http://localhost:8003'+path,{data:body,headers:{'Idempotency-Key':randomUUID()}});expect(r.ok(),await r.text()).toBeTruthy();return r.json();}
test('one $1000 check applies $300, $450 and $250; original aging and receipt history agree',async({page,prefix},info)=>{
 const c=await fixture(page,prefix);await start(page,c);await expect(page.getByText('Original statement',{exact:true})).toHaveCount(3);await expect(page.getByRole('table')).not.toContainText(/Statement #\d+/);await expect(page.getByRole('button',{name:'Review payment',exact:true})).toBeEnabled();await page.screenshot({path:info.outputPath('receive-payment.png'),fullPage:true,animations:'disabled'});for(const [i,amount]of [[1,'300.00'],[2,'450.00'],[3,'250.00']])await expect(page.getByLabel('Apply to '+prefix+'-INV'+i)).toHaveValue(amount);expect((await save(page)).status()).toBe(200);await expect(page.getByText(/saved. Applied \$1000.00/)).toBeVisible();const r=rows(`SELECT * FROM payment_receipts WHERE account_id=9001 AND customer_id=${c.id} AND source_kind='manual'`);expect(r).toHaveLength(1);expect(rows(`SELECT amount FROM ar_applications WHERE receipt_id=${r[0].receipt_id} ORDER BY application_id`).map(a=>Number(a.amount))).toEqual([300,450,250]);await page.getByRole('link',{name:'View receipt'}).click();await expect(page.getByRole('heading',{name:'Receipt #'+r[0].receipt_id,exact:true})).toBeVisible();
 await page.goto('/receivables/aging');await page.getByPlaceholder('Search by business name, customer name, display name, or ID').fill(prefix);await page.getByRole('button',{name:'Search',exact:true}).click();const row=page.getByRole('row').filter({hasText:c.name});await expect(row).toContainText('$150.00');await expect(row.locator('td').nth(4)).toContainText('$150.00');await expect(row.locator('td').nth(5)).not.toContainText('$150.00');await page.screenshot({path:info.outputPath('receive-aging.png'),fullPage:true});
 // A real subsequent issue establishes a carrier; the reconstructed opening above has none yet.
 const originalDate=rows(`SELECT to_char(invoice_date,'YYYY-MM-DD') AS day FROM customer_invoices WHERE account_id=9001 AND customer_id=${c.id} AND invoice_number=${literal(prefix+'-INV3')}`)[0].day;
 await createJob(page,c);const d=await openForm(page,routes.transactions,'New Charge');await choose(page,d,'Select Customer',c.name);await choose(page,d,'Select Job','1040 Individual Return');await choose(page,d,'Select Team Member','Eliza Smith');await choose(page,d,'General Work Description','Tax Return Preparation');await d.getByLabel('Work Completed On Job').fill(prefix+' carry-forward bill');await d.getByLabel('Quantity',{exact:true}).fill('1');await d.getByLabel('Unit Cost').fill('25');await submit(page,d,'/transactions/createTransaction/');await closeForm(page);
 await finalize(page,c,{entityId:c.entityId,expectedTotal:'175.00',testInfo:info});
 await page.goto(`/payments/receive?customerId=${c.id}&entityId=${c.entityId}`);
 const carried=page.getByRole('row').filter({hasText:prefix+'-INV3'});await expect(carried).toContainText('Later statement');await expect(carried).toContainText(originalDate);await expect(carried).toContainText('$150.00');await expect(page.getByRole('table')).not.toContainText(/Statement #\d+/);
 await page.getByLabel('Amount received',{exact:true}).fill('175');await expect(page.getByLabel('Apply to '+prefix+'-INV3')).toHaveValue('150.00');await expect(page.getByText('Original statement',{exact:true})).toHaveCount(1);
 await page.screenshot({path:info.outputPath('receive-after-rollover.png'),fullPage:true});
});
for(const [value,pattern]of [['0',/Allocation lines must be positive/],['-1',/Allocation lines must be positive/],['300.001',/Allocation lines must be positive/],['1001',/Applied total exceeds/],['301',/allocation exceeds/]])test(`blocks mistaken application ${value} before posting`,async({page,prefix})=>{const c=await fixture(page,prefix);await start(page,c,value==='301'?'1500':'1000');const before=state(c);await page.getByLabel('Apply to '+prefix+'-INV1').fill(value);await expect(page.getByText(pattern)).toBeVisible();await expect(page.getByRole('button',{name:'Review payment',exact:true})).toBeDisabled();expect(state(c)).toEqual(before);});
test('a concurrent payment produces a stale warning, preserves the check and refreshes amounts',async({page,prefix})=>{
 // The other operator uses the same displayed business date; UTC may already be tomorrow.
 const c=await fixture(page,prefix);await start(page,c);const open=await api(page,`/payments/open-obligations?customerId=${c.id}&entityId=${c.entityId}`);await api(page,'/payments/receipts',{customerId:c.id,entityId:c.entityId,amount:10,date:await page.getByLabel('Payment date',{exact:true}).inputValue(),method:'cash',reference:'',allocations:[{obligationId:open.obligations[0].obligation_id,amount:10}],ledgerFingerprint:open.ledgerFingerprint});const before=state(c);expect((await save(page)).status()).toBe(409);await expect(page.getByText(/open invoices or credit changed/)).toBeVisible();expect(state(c)).toEqual(before);await expect(page.getByLabel('Amount received')).toHaveValue('1000');await page.getByRole('button',{name:'Refresh open invoices'}).click();await expect(page.getByLabel('Apply to '+prefix+'-INV1')).toHaveValue('290.00');expect((await save(page)).status()).toBe(200);
});
for(const field of ['customerId','entityId','obligationId'])test(`server rejects a tampered wrong ${field} and the screen preserves the receipt`,async({page,prefix})=>{
 const c=await fixture(page,prefix);await start(page,c);const before=state(c);await page.route('**/payments/receipts',async route=>{if(route.request().method()!=='POST')return route.continue();const body=route.request().postDataJSON();if(field==='obligationId'){body.allocations[0].obligationId=2147483646;body.reason='Client specified invoice';}else body[field]=2147483646;await route.continue({postData:JSON.stringify(body)});});expect((await save(page)).status()).toBe(404);await expect(page.getByRole('alert')).toBeVisible();expect(state(c)).toEqual(before);await expect(page.getByLabel('Check / payment reference')).toHaveValue(prefix+'-CHECK');
});
test('whole receipt bounce restores all three original debts; partial reversal is refused',async({page,prefix})=>{
 const c=await fixture(page,prefix);await start(page,c);expect((await save(page)).status()).toBe(200);await page.getByRole('link',{name:'View receipt'}).click();const rid=Number(page.url().split('/').pop());await page.getByLabel('Reason for correction').fill('Bank returned the complete check');await page.getByRole('button',{name:'Flag complete receipt as bounced'}).click();await expect(page.getByRole('button',{name:'Reverse complete receipt'})).toBeVisible();const before=state(c);await page.route(`**/payments/receipts/${rid}/reversals`,async route=>route.continue({postData:JSON.stringify({...route.request().postDataJSON(),amount:1})}));await page.getByRole('button',{name:'Reverse complete receipt'}).click();await expect(page.getByText(/partial reversal is not permitted/)).toBeVisible();expect(state(c)).toEqual(before);await page.unroute(`**/payments/receipts/${rid}/reversals`);await page.getByLabel('Reason for correction').fill('Return the whole receipt');await page.getByRole('button',{name:'Reverse complete receipt'}).click();await expect(page.getByText(/The whole receipt is reversed/)).toBeVisible();const open=await api(page,`/payments/open-obligations?customerId=${c.id}&entityId=${c.entityId}`);expect(open.obligations.map(o=>o.openCents)).toEqual([30000,45000,40000]);
});
test('$1500 leaves $350 held credit, next $500 bill uses it once, and finalized applications stay locked',async({page,prefix},info)=>{
 const c=await fixture(page,prefix);await start(page,c,'1500');await expect(page.getByText('Remaining credit: $350.00')).toBeVisible();expect((await save(page)).status()).toBe(200);const receipt=rows(`SELECT * FROM payment_receipts WHERE account_id=9001 AND customer_id=${c.id} AND source_kind='manual'`)[0];await createJob(page,c);const d=await openForm(page,routes.transactions,'New Charge');await choose(page,d,'Select Customer',c.name);await choose(page,d,'Select Job','1040 Individual Return');await choose(page,d,'Select Team Member','Eliza Smith');await choose(page,d,'General Work Description','Tax Return Preparation');await d.getByLabel('Work Completed On Job').fill(prefix+' next bill');await d.getByLabel('Quantity',{exact:true}).fill('1');await d.getByLabel('Unit Cost').fill('500');await submit(page,d,'/transactions/createTransaction/');await closeForm(page);await page.goto(`/clients/${c.id}/auditRecord`);await expect(page.getByText('Held receipt credit $350.00 · Proposed next statement after credit $150.00')).toBeVisible();await finalize(page,c,{entityId:c.entityId,expectedTotal:'150.00',testInfo:info});await page.goto('/payments/receipts/'+receipt.receipt_id);await expect(page.getByText(/Finalized applications are locked/)).toBeVisible();await expect(page.getByLabel('Application to correct').locator('option')).toHaveCount(1);await expect(page.getByRole('button',{name:'Correct application',exact:true})).toBeDisabled();await expect(page.getByText(/\$0.00 available/)).toBeVisible();
});
test('a similar check needs a reason; duplicate cash can be cancelled only as a complete unissued receipt',async({page,prefix})=>{
 const c=await fixture(page,prefix);await start(page,c,'100');expect((await save(page)).status()).toBe(200);await page.getByLabel('Amount received').fill('100');await page.getByLabel('Check / payment reference').fill(prefix+'-CHECK');const before=state(c);expect((await save(page)).status()).toBe(409);await expect(page.getByText(/Possible duplicate receipt/)).toBeVisible();expect(state(c)).toEqual(before);await page.getByLabel('Reason to record a similar receipt').fill('Separate checks legitimately share this reference');expect((await save(page)).status()).toBe(200);await page.getByRole('link',{name:'View receipt'}).click();const rid=Number(page.url().split('/').pop()),flag=rows(`SELECT duplicate_id FROM duplicate_flags WHERE account_id=9001 AND kind='payment_receipt' AND record_id=${rid}`)[0];expect(flag).toBeTruthy();await page.goto('/work/duplicates?duplicateId='+flag.duplicate_id);await page.getByLabel('Reason',{exact:false}).fill('Review the complete cash receipt');await expect(page.getByRole('button',{name:'Remove duplicate',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Open receipt',exact:true}).click();await page.getByLabel('Reason for correction').fill('Second receipt was entered in error');await page.getByRole('button',{name:'Cancel unissued receipt entered in error'}).click();await expect(page.getByText(/complete receipt was reversed/)).toBeVisible();expect(rows(`SELECT kind FROM receipt_events WHERE account_id=9001 AND customer_id=${c.id} AND kind='exception_flagged'`)).toHaveLength(0);
});
test('admin corrects a single unissued application with visible preserved history',async({page,prefix})=>{
 const c=await fixture(page,prefix);await start(page,c,'100');expect((await save(page)).status()).toBe(200);await page.getByRole('link',{name:'View receipt'}).click();await page.getByLabel('Reason for correction').fill('Client requested the advisory invoice allocation');await page.getByLabel('Application to correct').selectOption({index:1});await page.getByLabel('Correct open invoice').selectOption({label:prefix+'-INV2 · $450.00'});await page.getByRole('button',{name:'Correct application',exact:true}).click();await expect(page.getByText('Application corrected with preserved history.')).toBeVisible();const open=await api(page,`/payments/open-obligations?customerId=${c.id}&entityId=${c.entityId}`);expect(open.obligations.map(o=>o.openCents)).toEqual([30000,35000,40000]);await expect(page.getByText(/application corrected · Client requested/)).toBeVisible();
});
test('admin transfers held receipt credit with cap, reason and double-click protection',async({page,prefix})=>{
 const c=await fixture(page,prefix);await start(page,c,'1500');expect((await save(page)).status()).toBe(200);const b=JSON.parse(sql(`INSERT INTO billing_entities(account_id,name,legal_name,invoice_prefix,is_default,active) VALUES(9001,${literal(prefix+' Advisory')},${literal(prefix+' Advisory')},${literal('H'+require('crypto').randomBytes(5).toString('hex').replace(/[0-9]/g,'A').toUpperCase())},false,true) RETURNING row_to_json(billing_entities)`));
 await page.goto('/payments/transfers');await page.getByLabel('Receipt credit client').selectOption(String(c.id));await page.getByLabel('Receipt credit from business').selectOption(String(c.entityId));await page.getByLabel('Receipt credit to business').selectOption(String(b.billing_entity_id));await page.getByLabel('Unused receipt credit').selectOption({index:1});await page.getByLabel('Receipt credit transfer reason').fill('Funds for advisory services');await page.getByLabel('Receipt credit transfer amount').fill('351');await expect(page.getByRole('button',{name:'Transfer receipt credit',exact:true})).toBeDisabled();await expect(page.getByText('Amount exceeds available receipt credit.')).toBeVisible();await page.getByLabel('Receipt credit transfer amount').fill('100');const posted=page.waitForResponse(r=>r.url().endsWith('/credits/transfers') && r.request().method()==='POST');await page.getByRole('button',{name:'Transfer receipt credit',exact:true}).dblclick();expect((await posted).status()).toBe(200);await expect(page.getByText('Unused receipt credit transferred; no new cash recorded.')).toBeVisible();expect(rows(`SELECT * FROM client_credit_events WHERE account_id=9001 AND customer_id=${c.id} AND kind='transfer'`)).toHaveLength(1);expect(rows(`SELECT * FROM payment_receipts WHERE account_id=9001 AND customer_id=${c.id} AND source_kind='manual'`)).toHaveLength(1);
});


test('AR reproduces an effective date and a saved knowledge cutoff without resetting debt ages',async({page,prefix})=>{
 const c=await fixture(page,prefix);await start(page,c);const recordedThrough=new Date().toISOString();expect((await save(page)).status()).toBe(200);
 await page.goto('/receivables/aging');await page.getByPlaceholder('Search by business name, customer name, display name, or ID').fill(prefix);await page.getByRole('button',{name:'Search',exact:true}).click();
 let row=page.getByRole('row').filter({hasText:c.name});await expect(row.locator('td').nth(4)).toContainText('$150.00');
 await page.getByRole('button',{name:'Advanced: reproduce an earlier report'}).click();await page.getByLabel('Include records saved through').fill(recordedThrough);
 await expect(row.locator('td').nth(4)).toContainText('$400.00');await expect(row.locator('td').nth(5)).toContainText('$450.00');await expect(row.locator('td').nth(6)).toContainText('$300.00');
 const prior=new Date();prior.setUTCDate(prior.getUTCDate()-20);await page.getByLabel('Aging as of').fill(prior.toISOString().slice(0,10));
 await expect(row.locator('td').nth(4)).toContainText('$450.00');await expect(row.locator('td').nth(5)).toContainText('$300.00');
 await page.getByLabel('Include records saved through').fill('not-a-timestamp');await expect(page.getByRole('alert')).toBeVisible();
});


for(const role of ['manager','employee','super admin'])test(`receipt corrections honor the ${role} role in the browser`,async({page,prefix})=>{
 const c=await fixture(page,prefix);await start(page,c,'100');expect((await save(page)).status()).toBe(200);await page.getByRole('link',{name:'View receipt'}).click();const url=page.url(),before=state(c);
 const original=rows('SELECT access_level FROM users WHERE account_id=9001 AND user_id=90013')[0].access_level;
 try{
  sql(`UPDATE users SET access_level=${literal(role)} WHERE account_id=9001 AND user_id=90013`);
  await page.evaluate(value=>sessionStorage.setItem('accessLevel',value),role);await page.goto(url);
  if(role==='super admin'){
   await page.getByLabel('Reason for correction').fill('Authorized single administrator correction');await page.getByRole('button',{name:'Cancel unissued receipt entered in error'}).click();await expect(page.getByText(/complete receipt was reversed/)).toBeVisible();
  }else{
   await expect(page.getByText(role==='employee'?'You are not authorized to access this page.':'Only admins can correct applications or apply a bounced-check exception.')).toBeVisible();
   for(const name of ['Correct application','Flag complete receipt as bounced','Reverse complete receipt','Cancel unissued receipt entered in error','Create statement revisions','Roll correction into next statement'])await expect(page.getByRole('button',{name,exact:true})).toHaveCount(0);
   expect(state(c)).toEqual(before);
  }
 }finally{sql(`UPDATE users SET access_level=${literal(original)} WHERE account_id=9001 AND user_id=90013`);}
});
