const {test,expect}=require('../lib/fixtures');
const {createCustomer,finalize,routes}=require('../lib/ui');
const {rows,sql,literal}=require('../lib/db');
const {randomUUID}=require('crypto');
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const entity=()=>rows('SELECT billing_entity_id FROM billing_entities WHERE account_id=9001 AND is_default')[0].billing_entity_id;
const plans=c=>rows(`SELECT * FROM recurring_customers WHERE account_id=9001 AND customer_id=${c.id}`);
const occurrences=c=>rows(`SELECT * FROM recurring_charge_occurrences WHERE account_id=9001 AND customer_id=${c.id} ORDER BY period_start`);
async function api(page,path,body,method='post',key=randomUUID()){
 if(!path.startsWith('/recurringCustomer/'))throw Error('Only recurring fixture routes');
 const r=await page.request[method]('http://localhost:8003'+path,{data:body,headers:{'Idempotency-Key':key}});return {r,body:await r.json()};
}
async function form(page,c){await page.goto('/billing/recurring/new');await page.getByLabel(/^Client\s*\*?$/).selectOption(String(c.id));await expect(page.getByLabel(/^Billing business\s*\*?$/)).toHaveValue(String(entity()));await page.getByLabel('Services description').fill(c.prefix+' recurring services');await page.getByLabel(/^Recurring fee\s*\*?$/).fill('125');await page.getByLabel('Start date',{exact:true}).fill(today().slice(0,8)+'01');await page.getByLabel('Reason for plan change').fill('Client recurring service agreement');}
async function save(page){const promise=page.waitForResponse(r=>/\/recurringCustomer\/plans(?:\/\d+)?$/.test(r.url()) && ['POST','PATCH'].includes(r.request().method()));await page.getByRole('button',{name:'Save plan',exact:true}).click();return promise;}
async function fixture(page,prefix,more={}){const c=await createCustomer(page,prefix);await form(page,c);for(const [label,value]of Object.entries(more))await page.getByLabel(label,{exact:true}).fill(value);expect((await save(page)).status()).toBe(200);await expect(page).toHaveURL(/\/billing\/recurring\/\d+$/);return {...c,p:plans(c)[0]};}
async function generate(page){const p=page.waitForResponse(r=>r.url().endsWith('/recurringCustomer/prepare') && r.request().method()==='POST');await page.getByRole('button',{name:'Generate due charges',exact:true}).click();expect((await p).status()).toBe(200);await expect(page.getByRole('table',{name:'Recurring charges ready for billing'})).toBeVisible();}

test('plan screen validates zero/negative fee, end before start and missing reason, then saves a description-only plan',async({page,prefix})=>{
 const c=await createCustomer(page,prefix);await form(page,c);for(const amount of ['0','-1','1.001']){await page.getByLabel(/^Recurring fee\s*\*?$/).fill(amount);await page.getByRole('button',{name:'Save plan',exact:true}).click();await expect(page.getByRole('alert')).toContainText('positive fee');expect(plans(c)).toHaveLength(0);}
 await page.getByLabel(/^Recurring fee\s*\*?$/).fill('125');await page.getByLabel('End date (optional)',{exact:true}).fill('2020-01-01');await page.getByRole('button',{name:'Save plan',exact:true}).click();expect(plans(c)).toHaveLength(0);await page.getByLabel('End date (optional)',{exact:true}).fill('');await page.getByLabel('Reason for plan change').fill('');await page.getByRole('button',{name:'Save plan',exact:true}).click();expect(plans(c)).toHaveLength(0);await page.getByLabel('Reason for plan change').fill('Valid agreement');expect((await save(page)).status()).toBe(200);expect(plans(c)).toHaveLength(1);expect(plans(c)[0].job_id).toBeNull();await page.reload();await expect(page.getByLabel(/^Recurring fee\s*\*?$/)).toHaveValue('125.00');
});
test('opening Create Invoice prepares a fee with scheduling off and a second open creates no duplicate',async({page,prefix},info)=>{
 const c=await fixture(page,prefix);expect(occurrences(c)).toHaveLength(0);await page.goto(routes.createInvoice);await expect(page.getByRole('row').filter({hasText:c.name}).first()).toBeVisible();await expect(page.getByRole('table',{name:'Recurring charges ready for billing'}).getByRole('row').filter({hasText:c.name})).toContainText('$125.00');expect(occurrences(c)).toHaveLength(1);await page.reload();await expect(page.getByRole('table',{name:'Recurring charges ready for billing'}).getByRole('row').filter({hasText:c.name})).toContainText('$125.00');expect(occurrences(c)).toHaveLength(1);await page.screenshot({path:require('path').join(info.outputDir,'recurring-ready.png'),fullPage:true});
});
test('edit and skip require reasons, keep fees editable and never regenerate the skipped period',async({page,prefix})=>{
 const c=await fixture(page,prefix);await generate(page);const o=occurrences(c)[0];await page.getByRole('button',{name:`Edit recurring charge ${o.occurrence_id}`,exact:true}).click();await page.getByLabel('Charge amount',{exact:true}).fill('100');await page.getByRole('button',{name:'Save recurring change'}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('reason');await page.getByRole('dialog').getByLabel(/^Reason\s*\*?$/).fill('Reduced service agreement');await page.getByRole('button',{name:'Save recurring change'}).click();await expect(page.getByRole('table').getByRole('row').filter({hasText:c.name})).toContainText('$100.00');await page.getByRole('button',{name:`Skip recurring charge ${o.occurrence_id}`,exact:true}).click();await page.getByRole('dialog').getByLabel(/^Reason\s*\*?$/).fill('Already billed manually');await page.getByRole('button',{name:'Save recurring change'}).click();await expect(page.getByRole('table').getByRole('row').filter({hasText:c.name})).toContainText('Skipped');await generate(page);expect(occurrences(c)).toHaveLength(1);expect(occurrences(c)[0].state).toBe('skipped');
});
test('double-click generation and retry generate one period, and changed retry key is refused',async({page,prefix})=>{
 const c=await fixture(page,prefix);const response=page.waitForResponse(r=>r.url().endsWith('/recurringCustomer/prepare'));await page.getByRole('button',{name:'Generate due charges'}).dblclick();expect((await response).status()).toBe(200);expect(occurrences(c)).toHaveLength(1);const key=randomUUID(),body={entityId:entity(),customerId:c.id};const first=await api(page,'/recurringCustomer/prepare',body,'post',key);expect((await api(page,'/recurringCustomer/prepare',body,'post',key)).body).toEqual(first.body);expect((await api(page,'/recurringCustomer/prepare',{...body,billingDate:'2020-01-01'},'post',key)).r.status()).toBe(409);expect(occurrences(c)).toHaveLength(1);
});
test('plan rate edits preserve prepared charges and deactivation mid-period leaves them visible',async({page,prefix})=>{
 const c=await fixture(page,prefix);await generate(page);await page.getByLabel(/^Recurring fee\s*\*?$/).fill('200');await page.getByLabel('Reason for plan change').fill('Future service rate');expect((await save(page)).status()).toBe(200);expect(occurrences(c)[0].snapshot_amount).toBe(125);await page.getByLabel('Active plan').uncheck();await page.getByLabel('Reason for plan change').fill('Client paused');expect((await save(page)).status()).toBe(200);await expect(page.getByRole('table').getByRole('row').filter({hasText:c.name})).toContainText('$125.00');expect(plans(c)[0].is_recurring_customer_active).toBe(false);
});
test('stale plan save is refused and retains the entered rate and reason',async({page,prefix})=>{
 const c=await fixture(page,prefix);const current={customerId:c.id,entityId:entity(),description:'Newer agreement',amount:175,frequency:'monthly',billDay:1,startDate:today().slice(0,8)+'01',endDate:null,active:true,reason:'Concurrent update',expectedVersion:1};expect((await api(page,`/recurringCustomer/plans/${c.p.recurring_customer_id}`,current,'patch')).r.status()).toBe(200);await page.getByLabel(/^Recurring fee\s*\*?$/).fill('300');await page.getByLabel('Reason for plan change').fill('Old screen change');expect((await save(page)).status()).toBe(409);await expect(page.getByText('This plan changed. Reload before saving.')).toBeVisible();await expect(page.getByLabel(/^Recurring fee\s*\*?$/)).toHaveValue('300');expect(plans(c)[0].recurring_bill_amount).toBe(175);
});
test('catch-up caps preparation at12 and explicit skips remain skipped',async({page,prefix})=>{
 const c=await fixture(page,prefix,{'Start date':'2024-01-01','End date (optional)':'2025-02-28'});await generate(page);expect(occurrences(c)).toHaveLength(12);await expect(page.getByText(/2 due periods remaining/)).toBeVisible();await page.getByRole('button',{name:'Review catch-up'}).click();await page.getByLabel('Period action').selectOption('skip');await page.getByRole('dialog').getByLabel(/^Reason\s*\*?$/).fill('Remaining periods were already billed');await page.getByRole('button',{name:'Save recurring change'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(occurrences(c)).toHaveLength(14);expect(occurrences(c).filter(o=>o.state==='skipped')).toHaveLength(2);await generate(page);expect(occurrences(c)).toHaveLength(14);
});
test('finalizing locks recurring charges and the PDF includes the period',async({page,prefix},info)=>{
 const c=await fixture(page,prefix);await finalize(page,c,{expectedTotal:'125.00',testInfo:info});const o=occurrences(c)[0];expect(o.state).toBe('issued');await page.goto(`/billing/recurring/${c.p.recurring_customer_id}`);await expect(page.getByText('Finalized — locked')).toBeVisible();await expect(page.getByRole('button',{name:`Edit recurring charge ${o.occurrence_id}`})).toHaveCount(0);const before=rows(`SELECT * FROM customer_transactions WHERE account_id=9001 AND customer_id=${c.id}`);expect((await api(page,`/recurringCustomer/occurrences/${o.occurrence_id}/skip`,{expectedVersion:o.version,reason:'Wrong issued action'})).r.status()).toBe(409);expect(rows(`SELECT * FROM customer_transactions WHERE account_id=9001 AND customer_id=${c.id}`)).toEqual(before);
});
test('a server failure preserves plan input and a retry succeeds',async({page,prefix})=>{
 const c=await createCustomer(page,prefix);await form(page,c);await page.route('**/recurringCustomer/plans',route=>route.request().method()==='POST'?route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({status:500,message:'Injected save failure'})}):route.continue(),{times:1});expect((await save(page)).status()).toBe(500);await expect(page.getByText('Injected save failure')).toBeVisible();await expect(page.getByLabel(/^Recurring fee\s*\*?$/)).toHaveValue('125');expect(plans(c)).toHaveLength(0);expect((await save(page)).status()).toBe(200);expect(plans(c)).toHaveLength(1);
});
test('legacy recurring bookmark redirects and missing detail recovers clearly',async({page,prefix})=>{
 await fixture(page,prefix);await page.goto('/billing/recurring');await expect(page).toHaveURL(/\/billing\/recurring$/);await page.getByLabel('Find recurring plan').fill(prefix);await expect(page.getByRole('row').filter({hasText:prefix})).toHaveCount(1);await page.goto('/billing/recurring/2147483646');await expect(page.getByText('Recurring plan not found.')).toBeVisible();await expect(page.getByRole('button',{name:'Save plan',exact:true})).toHaveCount(0);
});
for(const role of ['manager','super admin','employee'])test(`recurring plans enforce ${role} permissions in UI and API`,async({page,prefix})=>{
 const c=await createCustomer(page,prefix),old=rows('SELECT access_level FROM users WHERE account_id=9001 AND user_id=90013')[0].access_level;
 try{sql(`UPDATE users SET access_level=${literal(role)} WHERE account_id=9001 AND user_id=90013`);await page.evaluate(role=>sessionStorage.setItem('accessLevel',role),role);await page.goto('/billing/recurring/new');if(role==='employee'){await expect(page.getByRole('button',{name:'Save plan',exact:true})).toHaveCount(0);expect((await api(page,'/recurringCustomer/plans',{customerId:c.id,entityId:entity()})).r.status()).toBe(403);expect(plans(c)).toHaveLength(0);}else{await form(page,c);expect((await save(page)).status()).toBe(200);}}
 finally{sql(`UPDATE users SET access_level=${literal(old)} WHERE account_id=9001 AND user_id=90013`);}
});

test('ordinary charge details direct edits and removal to recurring period controls',async({page,prefix})=>{
 const c=await fixture(page,prefix);await generate(page);const o=occurrences(c)[0];await page.goto(routes.transactions);await page.getByPlaceholder('Search transactions').fill(prefix);await page.locator(`[role="row"][data-id="${o.transaction_id}"]`).click();await expect(page.getByRole('link',{name:'Open recurring plan'})).toBeVisible();await expect(page.getByRole('button',{name:'Delete Transaction',exact:true})).toHaveCount(0);await page.getByRole('link',{name:'Open recurring plan'}).click();await expect(page).toHaveURL(new RegExp(`/billing/recurring/${c.p.recurring_customer_id}$`));expect(occurrences(c)[0].state).toBe('generated');
});

test('the customer form can create an annual recurring plan',async({page,prefix})=>{
 const {openForm,choose,submit}=require('../lib/ui'),d=await openForm(page,routes.customers,'Add Customer');
 await d.getByLabel('First Name',{exact:true}).fill(prefix);await d.getByLabel('Last Name',{exact:true}).fill('Annual');
 for(const [label,value]of Object.entries({'Street Address':'123 Sandbox Lane',City:'Phoenix',State:'AZ',Zip:'85001',Phone:'6025550100',Email:`${prefix.toLowerCase()}@example.com`}))await d.getByLabel(label,{exact:true}).fill(value);
 await d.getByLabel('Recurring billing',{exact:true}).check();await choose(page,d,'Subscription Frequency','Annual');await d.getByLabel('First of the Month',{exact:true}).check();await d.getByLabel('Recurring Amount',{exact:true}).fill('250');await submit(page,d,'/customer/createCustomer/');
 const c=rows(`SELECT customer_id AS id FROM customers WHERE account_id=9001 AND display_name=${literal(prefix+' Annual')}`)[0];expect(c).toBeTruthy();expect(plans(c)[0].subscription_frequency).toBe('Annual');expect(plans(c)[0].billing_entity_id).toBe(entity());
});
test('covered time follows its business while excess and manual billable choices stay independent',async({page,prefix})=>{
 const {openForm,choose,submit,createJob}=require('../lib/ui'),c=await fixture(page,prefix);await createJob(page,c);
 const otherResponse=await page.request.post('http://localhost:8003/billing-entities',{data:{name:prefix+' Advisory',legal_name:prefix+' Advisory',invoice_prefix:'HFOUR',reason:'Synthetic business coverage scenario'}});expect(otherResponse.status()).toBe(200);const other=(await otherResponse.json()).entity.billing_entity_id;
 const d=await openForm(page,routes.transactions,'Add Time');await choose(page,d,'Select Customer',c.name);await expect(d.getByLabel('Billable',{exact:true})).not.toBeChecked();await d.getByRole('combobox',{name:/Billing business/}).selectOption(String(other));await expect(d.getByLabel('Yes',{exact:true})).toHaveCount(0);await expect(d.getByLabel('Billable',{exact:true})).toBeChecked();await d.getByRole('combobox',{name:/Billing business/}).selectOption(String(entity()));await expect(d.getByLabel('Billable',{exact:true})).not.toBeChecked();
 await choose(page,d,'Select Job','1040 Individual Return');await choose(page,d,'Select Team Member','Eliza Smith');await choose(page,d,'General Work Description','Tax Return Preparation');await d.getByLabel('Yes',{exact:true}).check();await expect(d.getByLabel('Billable',{exact:true})).toBeChecked();await d.getByLabel('Billable',{exact:true}).uncheck();await d.getByLabel('Time (hours)').fill('0.6');await expect(d.getByLabel('Billable',{exact:true})).not.toBeChecked();await d.getByLabel('Work Completed On Job').fill(prefix+' covered effort');await submit(page,d,'/transactions/createTransaction/');
 const work=rows(`SELECT is_transaction_billable,is_excess_to_subscription,total_transaction FROM customer_transactions WHERE account_id=9001 AND customer_id=${c.id}`);expect(work).toHaveLength(1);expect(work[0]).toMatchObject({is_transaction_billable:false,is_excess_to_subscription:true,total_transaction:45});
});
