import React,{useCallback,useContext,useEffect,useRef,useState} from 'react';
import {Alert,Box,Button,Checkbox,FormControlLabel,Paper,Stack,Table,TableBody,TableCell,TableHead,TableRow,TextField,Typography} from '@mui/material';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {context} from '../../App';
import {entitiesCall,entityError} from '../../Services/ApiCalls/BillingEntitiesCalls';
const blank={name:'',legal_name:'',invoice_prefix:'',contact_name:'',email:'',phone:'',address_line1:'',address_line2:'',city:'',state:'',postal_code:'',country:'US',active:true,is_default:false,reason:''};
const labels={name:'Business name',legal_name:'Legal name',invoice_prefix:'Invoice prefix',contact_name:'Contact name',email:'Email',phone:'Phone',address_line1:'Street address',address_line2:'Address line 2',city:'City',state:'State',postal_code:'Postal code',country:'Country'};
export default function BillingEntitiesPage(){
 const {loggedInUser}=useContext(context),admin=['admin','super admin'].includes((loggedInUser?.accessLevel || '').toLowerCase());const {entityId}=useParams(),navigate=useNavigate();
 const gate=useRef(false);
 const [entities,setEntities]=useState([]),[form,setForm]=useState(blank),[aliases,setAliases]=useState([]),[alias,setAlias]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[logo,setLogo]=useState(''),[busy,setBusy]=useState(false);
 const editing=Boolean(entityId);const existing=entityId && entityId!=='new';
 const load=useCallback(async()=>{setError('');try{const data=await entitiesCall();setEntities(data.entities || []);if(existing){const detail=await entitiesCall(`/${entityId}`);setForm({...blank,...detail.entity,reason:''});setAliases(detail.aliases);setLogo(detail.entity.logo_key?(await entitiesCall(`/${entityId}/logo`)).dataUrl:'');}}catch(e){setError(entityError(e));}},[entityId,existing]);
 // Initialize a new route before the user can type. A late list response must
 // never replace a new business draft with blank fields.
 useEffect(()=>{if(!existing){setForm(blank);setAliases([]);setLogo('');}if(admin)load();},[admin,load,existing]);
 const action=async fn=>{if(gate.current)return;gate.current=true;setBusy(true);setError('');setMessage('');try{await fn();}catch(e){setError(entityError(e));}finally{gate.current=false;setBusy(false);}};
 if(!admin)return <Alert severity='info'>Only admins can manage billing businesses.</Alert>;
 const save=()=>action(async()=>{const body={...form,expectedVersion:form.version};const data=await entitiesCall(existing?`/${entityId}`:'',existing?'patch':'post',body);setForm({...blank,...data.entity,reason:''});setMessage('Business saved.');navigate(`/settings/entities/${data.entity.billing_entity_id}`);});
 const upload=file=>action(async()=>{if(!file)return;if(!form.reason.trim())throw new Error('Enter a reason before changing the logo.');if(file.size>750000)throw new Error('Choose a PNG or JPEG smaller than 750 KB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const data=await entitiesCall(`/${entityId}/logo`,'post',{base64,reason:form.reason,expectedVersion:form.version});setForm({...blank,...data.entity,reason:''});setLogo((await entitiesCall(`/${entityId}/logo`)).dataUrl);setMessage('Logo saved.');});
 return <Stack spacing={3} sx={{p:3,maxWidth:1100}}><Typography variant='h4'>Billing businesses</Typography><Typography>Keep each company’s invoices, payments and credits separate.</Typography>{error && <Alert severity='error'>{error}</Alert>}{message && <Alert severity='success'>{message}</Alert>}
 {!editing?<><Stack direction='row' spacing={2}><Button component={Link} to='/settings/entities/new' variant='contained'>Add business</Button><Button component={Link} to='/settings/entities/cutover'>Opening balances</Button><Button component={Link} to='/work/review/entities'>Review tracker businesses</Button></Stack><Paper sx={{overflowX:'auto'}}><Table><TableHead><TableRow>{['Business','Invoice prefix','Status','Default',''].map((v,i)=><TableCell key={i}>{v}</TableCell>)}</TableRow></TableHead><TableBody>{entities.map(e=><TableRow key={e.billing_entity_id}><TableCell>{e.name}</TableCell><TableCell>{e.invoice_prefix}</TableCell><TableCell>{e.active?'Active':'Inactive'}</TableCell><TableCell>{e.is_default?'Default':''}</TableCell><TableCell><Button component={Link} to={`/settings/entities/${e.billing_entity_id}`}>Edit {e.name}</Button></TableCell></TableRow>)}</TableBody></Table></Paper></>:<>
 <Button component={Link} to='/settings/entities' sx={{alignSelf:'start'}}>All businesses</Button><Box component='form' onSubmit={e=>{e.preventDefault();save();}}><Stack spacing={2}>{Object.entries(labels).map(([key,label])=><TextField key={key} label={label} required={['name','legal_name','invoice_prefix'].includes(key)} value={form[key] || ''} onChange={e=>setForm(f=>({...f,[key]:e.target.value}))} disabled={busy} inputProps={{maxLength:key==='invoice_prefix'?12:200}}/>)}<FormControlLabel label='Active business' control={<Checkbox checked={form.active} onChange={e=>setForm(f=>({...f,active:e.target.checked}))} disabled={busy}/>}/><FormControlLabel label='Default business for new entries' control={<Checkbox checked={form.is_default} onChange={e=>setForm(f=>({...f,is_default:e.target.checked}))} disabled={busy}/>}/><TextField label='Reason for change' required multiline value={form.reason} onChange={e=>setForm(f=>({...f,reason:e.target.value}))} inputProps={{maxLength:2000}}/><Button type='submit' disabled={busy} variant='contained'>{busy?'Saving…':'Save business'}</Button></Stack></Box>
 <Paper variant='outlined' sx={{p:3}}><Typography variant='h6'>Letterhead preview</Typography>{logo && <Box component='img' src={logo} alt='Business logo' sx={{maxWidth:240,maxHeight:120,objectFit:'contain'}} />}<Typography sx={{mt:2,fontWeight:700}}>{form.legal_name || 'Legal name'}</Typography>{[form.address_line1,form.address_line2,[form.city,form.state,form.postal_code].filter(Boolean).join(' '),form.email,form.phone].filter(Boolean).map((v,i)=><Typography key={i}>{v}</Typography>)}<Typography sx={{mt:2}}>Invoice {form.invoice_prefix || 'PREFIX'}-{new Date().getFullYear()}-00001</Typography></Paper>
 {existing && <><Button component='label' disabled={busy}>Upload PNG or JPEG logo<input hidden type='file' accept='image/png,image/jpeg' onChange={e=>upload(e.target.files[0])}/></Button><Typography variant='h6'>Tracker spellings</Typography><Typography>Only exact names and these spellings match. Misspellings stay in review.</Typography>{aliases.map(a=><Stack key={a.alias_id} direction='row' spacing={2}><Typography>{a.alias}</Typography><Button disabled={busy || !form.reason.trim()} onClick={()=>action(async()=>{await entitiesCall(`/${entityId}/aliases/${a.alias_id}`,'delete',{reason:form.reason});await load();})}>Remove unused spelling</Button></Stack>)}<TextField label='Tracker spelling' value={alias} onChange={e=>setAlias(e.target.value)}/><Button disabled={busy || !alias.trim() || !form.reason.trim()} onClick={()=>action(async()=>{await entitiesCall(`/${entityId}/aliases`,'post',{alias,reason:form.reason});setAlias('');await load();setMessage('Tracker spelling saved.');})}>Add tracker spelling</Button></>}
 </> }</Stack>;
}
