import CustomerPicker from '../../Components/Lookups/CustomerPicker';
import ReceiptCreditTransfer from '../Payments/ReceiptCreditTransfer';
import React,{useContext,useEffect,useRef,useState} from 'react';
import {Alert,Button,Stack,TextField,Typography} from '@mui/material';
import {context} from '../../App';
import EntityPicker from '../../Components/BillingEntities/EntityPicker';
import {entitiesCall,entityError} from '../../Services/ApiCalls/BillingEntitiesCalls';
import {fetchCustomerProfileInformation} from '../../Services/ApiCalls/FetchCalls';
export default function CreditTransferPage({customerData}){
 const {loggedInUser}=useContext(context),{accountID,userID,token}=loggedInUser;const admin=['admin','super admin'].includes((loggedInUser.accessLevel || '').toLowerCase());
 const [form,setForm]=useState({customerId:'',sourceEntityId:null,destinationEntityId:null,retainerId:'',amount:'',reason:''}),[funds,setFunds]=useState([]),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');const key=useRef(null),flight=useRef(false);
 const load=()=>entitiesCall('/transfers').then(r=>setHistory(r.transfers)).catch(e=>setError(entityError(e)));
 useEffect(()=>{load();},[]);
 useEffect(()=>{let live=true;setFunds([]);if(form.customerId)fetchCustomerProfileInformation(accountID,userID,form.customerId,token,null,'retainers').then(data=>{if(!live)return;if(data.status && data.status!==200){setError(data.message || 'Unable to load available credit.');return;}const all=data?.customerRetainersData?.customerRetainers || data?.accountRetainersData?.accountRetainers || data?.customerRetainerData?.customerRetainers || [];const latest=new Map();all.forEach(r=>{const root=r.parent_retainer_id || r.retainer_id;const old=latest.get(root);if(!old || new Date(r.created_at)>new Date(old.created_at) || (new Date(r.created_at).getTime()===new Date(old.created_at).getTime() && r.retainer_id>old.retainer_id))latest.set(root,r);});setFunds([...latest.values()].filter(r=>r.is_retainer_active && Number(r.current_amount)<0));}).catch(e=>{if(live)setError(entityError(e));});return()=>{live=false;};},[form.customerId,accountID,userID,token,message]);
 const change=(k,v)=>{key.current=null;setForm(f=>({...f,[k]:v,...(['customerId','sourceEntityId'].includes(k)?{retainerId:''}:{})}));};
 const chosen=funds.find(r=>r.retainer_id===Number(form.retainerId));
 const submit=async()=>{if(flight.current)return;flight.current=true;setBusy(true);setError('');setMessage('');if(!key.current)key.current=window.crypto.randomUUID();try{const result=await entitiesCall('/transfers','post',{...form,expectedSnapshotId:chosen?.retainer_id},{headers:{'Idempotency-Key':key.current}});setMessage(result.message);key.current=null;setForm(f=>({...f,retainerId:'',amount:'',reason:''}));await load();}catch(e){setError(entityError(e));}finally{flight.current=false;setBusy(false);}};
 return <Stack spacing={2} sx={{p:3,maxWidth:1000}}><Typography variant='h4'>Credit transfers between businesses</Typography><Typography>Move unused client funds with paired entries and a reason. This does not record new cash.</Typography>{error && <Alert severity='error'>{error}</Alert>}{message && <Alert severity='success'>{message}</Alert>}{!admin?<Alert severity='info'>Only admins can transfer credit. Managers and employees can view the history.</Alert>:<Stack component='form' spacing={2} onSubmit={e=>{e.preventDefault();submit();}}><CustomerPicker native customerData={customerData}   label='Client' value={form.customerId} InputLabelProps={{shrink:true}} required onChange={value=>change('customerId',value)} /><EntityPicker label='From business' value={form.sourceEntityId} all onChange={v=>change('sourceEntityId',v)}/><EntityPicker label='To business' value={form.destinationEntityId} all onChange={v=>change('destinationEntityId',v)}/><TextField select SelectProps={{native:true}} label='Available credit' value={form.retainerId} InputLabelProps={{shrink:true}} required onChange={e=>change('retainerId',e.target.value)}><option value=''>Choose unused credit</option>{funds.filter(r=>Number(r.billing_entity_id)===Number(form.sourceEntityId)).map(r=><option key={r.retainer_id} value={r.retainer_id}>{r.display_name} — ${(-Number(r.current_amount)).toFixed(2)} available</option>)}</TextField><TextField label='Amount to transfer' type='number' inputProps={{min:0.01,step:0.01,max:chosen?-Number(chosen.current_amount):undefined}} value={form.amount} onChange={e=>change('amount',e.target.value)} required/><TextField label='Reason for transfer' multiline required value={form.reason} onChange={e=>change('reason',e.target.value)} inputProps={{maxLength:2000}}/><Button type='submit' variant='contained' disabled={busy || !chosen || !form.destinationEntityId || form.sourceEntityId===form.destinationEntityId}>{busy?'Transferring…':'Transfer credit'}</Button></Stack>}<ReceiptCreditTransfer customerData={customerData}/><Typography variant='h6'>Retainer transfer history</Typography>{history.length?history.map(t=><Typography key={t.transfer_id}>{t.client_name || `Client ${t.customer_id}`} · {t.source_name || `Business ${t.billing_entity_id}`} → {t.destination_name || `Business ${t.destination_entity_id}`} · ${Number(t.amount).toFixed(2)} · {t.reason}</Typography>):<Typography>No credit transfers.</Typography>}</Stack>;
}
