import React,{useCallback,useContext,useEffect,useRef,useState} from 'react';
import {Alert,Button,Paper,Stack,TextField,Typography} from '@mui/material';
import {context} from '../../App';
import {entitiesCall,entityError} from '../../Services/ApiCalls/BillingEntitiesCalls';
import EntityPicker from '../../Components/BillingEntities/EntityPicker';
export default function EntityReviewPage(){
 const {loggedInUser}=useContext(context);const admin=['admin','super admin'].includes((loggedInUser?.accessLevel || '').toLowerCase());
 const gate=useRef(false);
 const [rows,setRows]=useState([]),[total,setTotal]=useState(0),[offset,setOffset]=useState(0),[drafts,setDrafts]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError('');setRows([]);try{const data=await entitiesCall(`/review?limit=25&offset=${offset}`);setRows(data.reviews);setTotal(data.totalCount);}catch(e){setError(entityError(e));}finally{setLoading(false);}},[offset]);
 useEffect(()=>{if(admin)load();},[admin,load]);
 if(!admin)return <Alert severity='info'>Only admins can resolve a business assignment. Other work remains available.</Alert>;
 const choose=(row,key,value)=>setDrafts(d=>({...d,[row.review_id]:{...d[row.review_id],[key]:value}}));
 const resolve=async row=>{if(gate.current)return;gate.current=true;setBusy(true);setError('');try{await entitiesCall(`/review/${row.review_id}/resolve`,'post',{...drafts[row.review_id],expectedSourceHash:row.sourceHash});await load();}catch(e){setError(entityError(e));}finally{gate.current=false;setBusy(false);}};
 return <Stack spacing={2} sx={{p:3,maxWidth:1100}}><Typography variant='h4'>Business assignments needing review</Typography><Typography>{total} entries need an explicit business before billing. {total>0 && <>Showing {offset+1}–{Math.min(offset+25,total)}.</>}</Typography>{error && <Alert severity='error'>{error}</Alert>}{loading && <Typography role='status'>Loading business assignments…</Typography>}{!loading && !error && !rows.length && <Alert severity='success'>No business assignments need review.</Alert>}<Stack direction='row' spacing={2}><Button disabled={loading || busy || offset===0} onClick={()=>setOffset(v=>Math.max(0,v-25))}>Previous</Button><Button disabled={loading || busy || offset+25>=total} onClick={()=>setOffset(v=>v+25)}>Next</Button></Stack>{rows.map(row=><Paper key={row.review_id} variant='outlined' sx={{p:2}}><Stack spacing={2}><Typography variant='h6'>{row.raw_entity || 'No verified tracker business'}</Typography><Typography title={row.customer_id?`Client ID: ${row.customer_id}`:undefined}>Client {row.customer_name || row.source.company_name || (row.customer_id?'name not recorded':'not yet matched')} · {String(row.source.transaction_date || row.source.date || '').slice(0,10)}</Typography><Typography>{row.source.detailed_work_description || row.source.notes || 'No description'}</Typography><EntityPicker value={drafts[row.review_id]?.entityId} all label='Assign billing business' onChange={v=>choose(row,'entityId',v)}/><TextField label='Reason for assignment' multiline value={drafts[row.review_id]?.reason || ''} onChange={e=>choose(row,'reason',e.target.value)} inputProps={{maxLength:2000}}/><Button disabled={loading || busy || !drafts[row.review_id]?.entityId || !drafts[row.review_id]?.reason?.trim()} onClick={()=>resolve(row)} variant='contained'>Save assignment</Button></Stack></Paper>)}</Stack>;
}
