/* The single source for in-app help and docs/platform/page-help.md.
 * Run: node DS2_Backend/scripts/docs/generate-page-help.js (from the DS2 folder).
 * Keep role rules, issued-record locks and cash/credit distinctions in sync with the feature docs.
 */
const operators = 'Managers, admins, super admins and the legacy owner role can use this page.';
const adjustments = 'Managers and admins may view these records. Only admins and super admins may apply adjustments, acting alone with a reason.';
const reports = 'Super admins can use these reports. Opening or exporting a report does not change the ledger.';
const entry = (title, purpose, use, effect, who, correction) => ({ title, bullets: [
  `What: ${purpose}`, `Use: ${use}`, `Business effect: ${effect}`, `Who: ${who}`, `Correcting mistakes: ${correction}`
] });
const pageHelp = {
  '/clients': entry('Clients', 'Find client contact details, work, statements and money history in one place.', 'Search for an existing client before creating another. Open the client profile for their records.', 'Contact changes do not create charges or payments. Financial activity remains separate for each of our businesses and is recorded in the audit history.', operators, 'Edit contact details when needed. Clients with financial history cannot simply be deleted; correct their records through the matching workflow.'),
  '/work/entries': entry('Work entries', 'Record time and charges for a client and the business doing the work.', 'Choose the client, our business and job before entering work. Use Receive payment for money received.', 'Billable work adds to unbilled work, not billed revenue until finalized. Time rounds up once to six-minute units; actual effort and captured staff cost support reports.', operators, 'Edit or delete unissued work. Finalized work is locked; an admin uses a credit memo or Void and rebill. Generated recurring fees are changed through their period controls.'),
  '/work/jobs': entry('Client jobs', 'Organize the services and rates used for a client’s work.', 'Search within the selected client and business. Create a job before recording work that needs it.', 'A job alone creates no receivable or cash. Its rates guide new work; historical issued charges stay unchanged. Changes are audited.', operators, 'Edit eligible job details. Referenced jobs may require correction of their dependent records before deletion; sent records stay locked.'),
  '/work/review': entry('Work review', 'Review imported time, client and job matches, rates and held entries before billing.', 'Resolve missing or incorrect information here; use Business assignments for unresolved tracker business names.', 'Only accepted billable work reaches billing. Covered recurring time remains separate from excess billable work; saved corrections retain their actor and reason.', operators, 'Fix unissued work with a reason and recheck the client and business. Issued work requires an admin correction document.'),
  '/work/review/entities': entry('Business assignments', 'Resolve tracker entries whose business name could not be matched safely.', 'Choose the actual business for new held work. Use Billing businesses to maintain names and exact aliases.', 'Resolving new work can make it eligible for billing in that business. Historical tracker attribution alone does not move old balances; decisions are audited.', 'Admins and super admins manage business assignments.', 'A reason is required. Move only eligible unissued work; already issued records need an admin correction. Never create a business from a mistyped client name.'),
  '/work/duplicates': entry('Possible duplicates', 'Review records that may represent the same work or money more than once.', 'Compare the records and source evidence. Dismiss a false alarm; use the sent-record correction process for a finalized duplicate.', 'Flagging or dismissing changes no balance. Removing a permitted duplicate changes its financial effects and leaves audit evidence.', 'Managers and admins may review and flag. Only admins and super admins may remove a record that holds money, without a second approver.', 'A flag never unlocks sent records. Removal cannot erase issued evidence; use an admin correction and keep a clear reason.'),
  '/billing/create': entry('Create invoices', 'Prepare and finalize each client’s statement for one of our businesses.', 'Review ready recurring charges, unbilled work, balance forward and proposed credit use. Preview a draft before finalizing.', 'Finalize means sent and locked. New charges count as billed revenue; old debt carries forward without becoming new revenue or getting a younger age. Held credit is applied once.', operators, 'Drafts stay editable. Finalized invoices and their records cannot be edited; admins use a credit memo, Void and rebill or the specific bounced-check process. Credit statements require individual selection.'),
  '/billing/invoices': entry('Invoices', 'Find original statements, their current balances and correction history.', 'Open an invoice to view its details or reprint its original. Use Create invoices for the next billing cycle.', 'Reprinting changes no debt, cash, revenue or aging. Current balances can differ from the original after later payments and corrections.', operators, 'Finalized originals stay locked. Only admins and super admins can issue credit memos, Void and rebill or bounced-check corrections, with a reason.'),
  '/billing/invoices/:invoiceId': entry('Invoice details and Void and rebill', 'See the original invoice, work, payments, carried balance and linked corrections.', 'Use a credit memo for a post-issue discount or overcharge. Use Void and rebill to replace the invoice’s new charges.', 'Void and rebill keeps the original and issues a replacement with a new invoice number. It preserves payment history and handles excess as credit; moving funds between businesses must be explicit.', 'Managers and admins may read and reprint. Admins only: credit memos, Void and rebill and bounced-check corrections; super admins also qualify and no second approval is needed.', 'Finalized originals and replacement invoices are locked. Correct with linked documents and a reason; never edit the old invoice or count carried debt as a new charge.'),
  '/billing/credit-memos': entry('Credit memos', 'A credit memo lowers what a client owes on an invoice that was already sent, without changing the original invoice.', 'Correct an overcharge or give a discount after finalization. To replace the whole invoice, use Void and rebill instead.', 'It reduces the client’s balance and that invoice’s aging, and appears once on the next statement. Reports count it as a credit: lower billed revenue, not a payment or write-off. If already paid, the extra becomes client credit for the next bill or a refund.', 'Managers and admins may view. Only admins and super admins may issue or reverse a memo, acting alone with a reason.', 'A memo cannot be edited. Reverse a mistake with a linked document; the memo and original invoice remain preserved in the audit history.'),
  '/billing/quotes': entry('Quotes', 'Review proposed prices before billing a client.', 'This register is read-only. Review agreed services here, record actual work through Work entries and use Create invoices when ready to bill.', 'A quote is not an issued invoice, cash receipt or receivable and does not add billed revenue or aging. Changes remain part of the audit history.', operators, 'Correct a quote before relying on it. Editing a quote does not alter a separate finalized invoice; an admin must correct that invoice explicitly.'),
  '/billing/recurring': entry('Recurring plans', 'Set a client’s recurring fee, business and billing calendar.', 'Choose the amount, frequency and start date once. Review generated periods here or in Create invoices; use ordinary work entry for extra services.', 'Opening Create invoices prepares due fees even when scheduled jobs are off. Each period is generated once and becomes billed revenue only at finalization. Covered time and excess work remain separate.', operators, 'Plan edits affect future unprepared periods. Edit or skip ready periods with a reason; issued periods stay locked. Older excluded periods require explicit catch-up confirmation.'),
  '/payments/receive': entry('Receive payment', 'Record one cash or check payment and apply it across a client’s open invoices.', 'Select the correct client and our business, then review oldest-first amounts. Explain a different allocation. Use a credit memo for a discount, not a payment.', 'Applications reduce original invoice balances and aging. Any remainder becomes held client credit for that business, used on a later bill or explicitly refunded. Cash is recorded once; there is no bank connection.', operators, 'Review before recording and refresh stale balances. Only admins can correct or cancel an unissued receipt or handle a whole bounced check; finalized applications stay locked and every correction is audited.'),
  '/payments/receipts': entry('Payment receipts', 'Find received payments and their invoice applications or remaining credit.', 'Open a receipt to trace a check across invoices. Use Receive payment to enter new money; use the legacy register for older payment records.', 'A receipt records cash once. Applying or moving its credit does not create another receipt or billed revenue. Original debt keeps its age.', operators, 'Only admins and super admins correct allocations, cancel eligible entry mistakes or flag and reverse a complete bounced check, with a reason. Issued history cannot be erased.'),
  '/payments/receipts/:receiptId': entry('Receipt details', 'Trace one payment, its invoice applications, remaining credit and correction history.', 'Use this page to review allocations or investigate a returned check. A historical receipt points to its original payment or retainer workflow.', 'A whole bounced-check reversal restores all its applications at their original ages and removes remaining credit. Refunds or consumed funds may block reversal; no partial bounce is allowed.', adjustments, 'Unissued applications can be corrected without changing cash received. Issued applications stay locked. After an allowed reversal, an admin chooses statement revisions or the next statement; all earlier evidence remains.'),
  '/payments/imports': entry('Payment imports', 'Review extracted payment information before recording it in the ledger.', 'Check the client, our business, amount, reference and invoice against the source image. Use Receive payment for a manual check covering multiple invoices.', 'A pending import is not cash posted to the account. Accepting it records the payment once and applies the supported invoice or retainer effect, with audit history.', operators, 'Fix pending details before accepting. Repeated acceptance must not post twice; already posted money uses the authorized payment correction workflow.'),
  '/payments/credits': entry('Client credits', 'See unused receipt money and credits created by issued statements or correction documents.', 'Select the client and business to review available credit. Use Retainers & deposits for separately recorded retainers.', 'Held receipt credit does not reduce invoice debt until applied. Refunding it reduces funds held; refunding issued statement credit brings its negative billed balance toward zero. Credit itself is not new cash.', adjustments, 'Admins record actual money returned with date, method, reference and reason. Refunds are permanent journal entries; used or exhausted credit cannot be refunded again.'),
  '/payments/retainers': entry('Retainers and credits', 'Record deposits held for future work and inspect their remaining availability.', 'Use a retainer for funds specifically held this way. Use Receive payment for a check to allocate among invoices and Client credits for receipt overpayments.', 'A deposit records cash and available funds, not new billed revenue. Applications consume available funds once. Refunds and adjustments change availability without reducing invoice debt a second time.', 'Managers and admins may record deposits. Only admins and super admins may refund or adjust them, acting alone with a reason.', 'Unissued receipts have guarded edit and delete controls. Sent originals and saved refund or adjustment events cannot be edited; record a permitted new event and retain the history.'),
  '/payments/refunds': entry('Refund history', 'Review documents for money returned from client credit.', 'Download a refund record or trace its source. Start a new refund from Client credits; use the client’s retainer tab for retainer refunds.', 'Refunds reduce available credit and record cash returned. They are not new charges, payments received or write-offs. Their source and reason remain in the audit history.', adjustments, 'Posted refund documents are locked. Review the source and amount before recording; an admin must make any further correction through a supported new entry.'),
  '/payments/transfers': entry('Credit transfers', 'Move available credit between our businesses for the same client.', 'Use an explicit transfer when the client’s funds belong with another business. Do not change the original receipt’s business or use a transfer to record new cash.', 'Equal credit-out and credit-in entries preserve total funds. Transfers create no cash or revenue and keep the original source and both businesses in the audit record.', 'Signed-in staff can open this page; financial reads retain their role limits. Only admins and super admins may post a transfer, alone with a reason.', 'Transfers are recorded events, not editable replacements. Used, reserved or insufficient funds cannot be moved; correct with a new permitted transfer and retain the original history.'),
  '/receivables/aging': entry('Accounts receivable', 'See what clients owe on issued invoices, grouped by the original age of the debt and our business.', 'Use the report for unpaid issued balances. Use WIP / Unbilled for work not yet invoiced, and Advanced to reproduce an earlier report.', 'Carrying debt onto a later statement never restarts its age. Issued credits and held receipt credit are shown separately. Historical estimates and unknown ages remain identified; reading the report changes nothing.', operators, 'Fix the underlying payment, work or invoice through its proper workflow, then refresh. Only admins apply adjustments; a report cannot edit locked invoices or erase audit history.'),
  '/receivables/write-offs': entry('Write-offs', 'Record an amount the firm decides not to collect or an allowed concession on unissued work.', 'Choose the correct client, our business and invoice or work. Use a payment for money received, a credit memo for an issued overcharge, and a refund for money returned.', 'A write-off reduces the relevant amount due or unbilled value. It is reported separately from cash and credit memos and leaves its reason and actor in the audit record.', adjustments, 'Only admins and super admins may create, edit or delete eligible write-offs. Sent write-offs stay locked; use a supported correction rather than changing issued evidence.'),
  '/reports/billing-performance': entry('Billing performance', 'Compare work entered, unbilled work, issued revenue, applied receipts and margin.', 'Choose matching dates and businesses. Use AR for unpaid invoice ages; use the cash figures when asking how much money was received or returned.', 'Billed revenue counts finalized new charges, less credit memos and voids, without counting balance forward twice. Margin uses captured staff costs; estimated or unknown costs are labeled.', reports, 'Changing filters changes only the report. Correct source records through their workflow; sent records require an admin correction and historical cost evidence is not overwritten by today’s rate.'),
  '/reports/client-rates': entry('Client rates', 'Compare client work, issued billing and effective rates.', 'Use the same period and business when comparing clients. Use Billing performance for the full revenue, receipt and margin breakdown.', 'Unbilled work is separate from issued revenue. Credit memos and voids reduce net billed amounts; missing cost or rate evidence is identified rather than guessed.', reports, 'Filters and exports are read-only. Correct source work before issue or use an admin correction for a finalized invoice; refreshing reflects those recorded events.'),
  '/reports/time-allocation': entry('Time allocation', 'Review where staff effort was spent across clients, services and businesses.', 'Use actual effort to understand workload, including covered or nonbillable time. Use billed-revenue reports to assess issued fees.', 'Worked-for business attribution describes effort and does not move historical client balances. Actual minutes and captured costs support margin; six-minute billing rounding is a separate calculation.', reports, 'Correct eligible source time with a reason. Finalized records and captured history remain protected; changing a staff rate does not reprice old labor cost.'),
  '/reports/wip-aging': entry('WIP / Unbilled', 'Find billable work that has not yet been finalized on an invoice.', 'Use this to prepare billing and investigate older unbilled work. Use Accounts receivable for already issued debt.', 'Unbilled work is not billed revenue or cash. Historical cutoffs show what was unbilled at that time; held work is distinguished from work ready to bill.', reports, 'Correct or release eligible work through Work review and bill through Create invoices. This report cannot change issued records or bypass required business assignments.'),
  '/reports/job-budgets': entry('Job budgets', 'Compare job expectations with recorded work and billing.', 'Use consistent dates, client and business selections to spot work needing review. Use the job or work page to change eligible inputs.', 'Budget analysis is read-only; it does not create debt, cash or adjustments. Issued revenue and captured cost evidence remain separate from entered work.', reports, 'Correct the job or unissued work at its source. An admin correction is required for issued charges; report filters never rewrite them.'),
  '/reports/tax-capacity': entry('Tax season capacity', 'Review staff workload and tax-season service capacity.', 'Use recorded effort and consistent reporting dates for planning. Use Account users to maintain authorized staff settings.', 'Planning views create no charge, cash or receivable. Covered time and actual effort remain visible; historical cost estimates are identified.', reports, 'Correct source time or future staff settings through the relevant page. Planning changes cannot edit sent invoices or rewrite prior cost evidence.'),
  '/reports/account-audit': entry('Account audit', 'Reconcile balances, unbilled work and available funds across clients and businesses.', 'Run a reconciliation when investigating a difference. Use the client’s Audit Record for the deterministic change history and immutable evidence documents.', 'The audit compares next-statement and issued-balance calculations without adding duplicate debt. It creates review evidence, not a payment, invoice or adjustment. Full audits run in the background.', reports, 'Investigate findings and correct underlying records through authorized workflows. An audit is not permission to edit sent records or apply non-admin adjustments.'),
  '/time-tracking/upload': entry('Upload time tracker', 'Submit a completed spreadsheet of staff work for validation and processing.', 'Use the current template and confirm its owner and dates. Correct rejected rows before uploading again; use Your trackers to follow progress.', 'Accepted rows can become work for billing after matching and business review. Time is billed in six-minute units and retains actual effort and initial cost evidence. Duplicate review prevents accidental reposting.', 'Signed-in staff can upload within their permitted ownership scope; managers and admins have the supported staff-management options.', 'Validation failures do not authorize guessing a client or business. Correct the source or held entry; sent work stays locked and needs an admin correction.'),
  '/time-tracking/history': entry('Your trackers', 'Follow your uploaded files and their validation or processing results.', 'Check status and errors before trying an upload again. Use Upload time tracker for a corrected file and Work review for authorized matching corrections.', 'Viewing or downloading history changes no balance. Only accepted posted work can affect billing; the uploaded source remains evidence.', 'Signed-in staff see their permitted tracker history; broader staff review belongs in Employee trackers.', 'Use the error explanation to correct the source. Do not re-enter already posted work to clear a status; finalized work requires an admin correction.'),
  '/time-tracking/trackingAdministration': entry('Employee trackers', 'Review staff tracker submissions, status and imported time.', 'Use this for staff-wide tracker follow-up. Use Work review for client, job and billing corrections; employees use Your trackers for their own files.', 'Tracker status is not a payment or invoice. Accepted work may feed billing; uploads, review decisions and processing retain audit evidence.', operators, 'Resolve validation or held-work problems at their source. Do not delete or rewrite sent work; use the supported admin correction workflow.'),
  '/settings/entities': entry('Business settings', 'Manage our billing businesses, legal names, invoice details and tracker aliases.', 'Add a real firm business or maintain an existing one. Client companies belong in Clients, not in this list.', 'Each business keeps its own balances, credit and invoice numbering. Old issued letterheads stay frozen. Changing a tracker alias does not automatically move old money.', 'Admins and super admins manage businesses. Any admin may act alone; financial transfers and reassignments require a reason.', 'Keep at least one active default business. Deactivate a referenced business instead of erasing its history; use explicit unissued-work moves or correction documents for mistaken financial assignments.'),
  '/settings/entities/cutover': entry('Opening balances', 'Review the initial business assignment of existing balances and funds.', 'Use only for a reviewed cutover or permitted amendment. Use normal billing and payment pages for current activity.', 'Pre-cutover open debt, unbilled work, pending adjustments and credits stay together in the default business unless explicitly reassigned. Other businesses start at zero; tracker attribution alone moves no money.', 'Admins and super admins review and apply eligible opening assignments with a reason.', 'Applied manifests and original records remain immutable. Stale or incompatible changes are refused; correct through a supported amendment before activity blocks it.'),
  '/settings/account': entry('Account settings', 'Maintain the firm account’s contact and general settings.', 'Use Billing businesses for each issuing company’s details and Account users for staff permissions.', 'General settings do not post cash or change client balances. Issued invoices retain their original saved details; account changes are audited.', 'Admins and super admins can edit account settings.', 'Review before saving and correct eligible settings here. Renaming the firm does not erase its storage ownership, issued documents or audit history.'),
  '/settings/users': entry('Account users', 'Manage staff access, identities and rates.', 'Choose the least access needed for the job. Admin and super admin are the only roles allowed to apply financial adjustments.', 'New staff cost rates apply to future recorded work; old captured costs and issued revenue stay unchanged. Access and rate changes are audited.', 'Super admins manage account users. A manager role does not grant adjustment authority.', 'Correct future settings here. Users referenced by history have guarded deletion; do not erase financial evidence to remove a staff member.'),
  '/settings/automations': entry('Automations', 'Choose supported account reminders and scheduled workflow preferences.', 'Maintain recipients and timing preferences here. Use recurring plans for client billing schedules.', 'Account preferences cannot override the server’s email and scheduler switches. This local sandbox suppresses real email and scheduled jobs. Due recurring charges still prepare when Create invoices opens.', 'Admins and super admins manage these account preferences.', 'Review recipient choices before saving. Turning a preference off does not undo previously recorded work or an already sent message; changes are audited.'),
  '/settings/job-categories': entry('Job categories', 'Maintain the categories that group your service types.', 'Choose clear names that staff can recognize. Use Job types for individual services and Client jobs to assign them.', 'A category is a reference label, not debt, revenue or cash. Changes are audited and referenced financial records keep their protected history.', operators, 'Edit eligible labels here. Deletion is guarded when dependent jobs or work still use the category; sent evidence cannot be removed.'),
  '/settings/job-types': entry('Job types', 'Maintain reusable service types and their pricing defaults.', 'Use these when setting up client jobs. Record performed services through Work entries.', 'Defaults guide new jobs and work; changing a type does not rewrite finalized charges or automatically create revenue. Changes are audited.', operators, 'Correct eligible defaults and inspect dependent records before deletion. Sent records stay locked and financial corrections are admin-only.'),
  '/settings/work-descriptions': entry('Work descriptions', 'Maintain reusable wording for work entries.', 'Use clear service descriptions so staff and clients can understand the work. Use Work entries to record actual services.', 'A description alone changes no balance or report total. Using it on work can support billing; updates are kept in audit history.', operators, 'Correct eligible wording here. Removing a referenced item is guarded and does not authorize rewriting sent invoice evidence.'),
  '/settings/tracker-template': entry('Tracker template', 'Maintain the spreadsheet template used for time uploads.', 'Use the supported workbook format and review the template before staff use it. Upload actual completed time on Upload time tracker.', 'Template changes affect future uploads, not existing work, invoices or cash. Validation protects the structure and account-specific information.', 'Super admins manage the shared tracker template.', 'Replace an incorrect template with a validated one. Existing accepted or issued work must be corrected through its own workflow; changing the template does not redo it.'),
  '/settings/tracker': entry('Tracker settings', 'Maintain staff and account choices used by time-tracker workflows.', 'Use this for tracker-specific settings. Use Account users for roles and cost rates, and Automations for reminder preferences.', 'Settings guide future processing and notifications; they do not themselves post debt or cash. Server email and scheduling switches still apply.', operators, 'Correct eligible settings here and review affected held work separately. Existing uploads and sent records are not silently rewritten.'),
  '/dashboard/app': entry('Dashboard', 'Open the workspace and navigate to the task you need.', 'Choose Clients for a client’s records or the grouped navigation for billing, payments, reports and settings.', 'Navigation changes no balance, cash or audit history. Financial changes occur only through their permitted workflow.', 'Signed-in staff see destinations allowed by their role.', 'Return to the appropriate page to correct an entry. Finalized records remain locked and only admins can apply adjustments.')
};
const client = (tab, title, purpose, use, effect, who, correction) => {
  pageHelp['/clients/:customerId'+(tab?'/'+tab:'')] = entry(title,purpose,use,effect,who,correction);
};
client('', 'Client overview', 'See a client’s contact details and current balances.', 'Select our business to inspect a single ledger, or all businesses for an overview. Open the relevant tab for detailed activity.', 'Issued balances, unbilled work and held funds are distinct amounts. Viewing the profile posts nothing and does not net funds between businesses.', operators, 'Edit contact details through Edit client. Correct money through its own workflow; finalized records stay locked and adjustments are admin-only.');
client('statements','Client statements','Review this client’s original statements and their later balance history.','Open an invoice for line details and correction documents. Use Create invoices to prepare the next statement.','Original totals stay frozen; later payments and corrections change the current balance. Carry-forward is not a second charge and does not reset aging.',operators,'Reprints change nothing. Admins correct sent invoices with linked documents; original invoices and PDFs cannot be edited.');
client('work','Client work','Review time and charges recorded for this client.','Check the selected business and service details. Use Work entries to record new work or Work review for held imports.','Billable unissued work contributes to the next bill; it is not yet billed revenue. Covered time remains effort for cost reporting without duplicating the recurring fee.',operators,'Edit eligible unissued work. Finalized records stay locked; admins use invoice corrections and generated recurring work uses its period controls.');
client('jobs','Client jobs','See this client’s jobs and service rates.','Choose the correct business and job for new work. Use the job catalog to maintain reusable service types.','Jobs guide work entry but do not themselves create debt, cash or billed revenue. Job and work changes are audited.',operators,'Edit eligible jobs; dependent work can prevent deletion. Changing a rate never rewrites a sent invoice.');
client('receipts','Client receipts','Review this client’s received payments and their applications.','Use Receive payment for this client to record a check across invoices. Choose our business before reviewing balances.','Cash is received once; invoice applications reduce the original debt, and unapplied excess stays as held credit for that business.',operators,'Only admins correct applications, cancel eligible unissued mistakes or process a whole bounced check with a reason. Finalized history stays locked.');
client('credits','Client credits and retainers','Review held retainers and their refund or adjustment history.','Use View client credits for unused receipt money or statement credit. Record an actual refund only when money is being returned.','Retainer events change available funds, not invoice debt a second time. Applications, refunds and noncash adjustments remain distinct in reports and the audit history.',adjustments,'Only admins and super admins may refund or adjust. Saved events cannot be edited; record a permitted new event and never remove funds already used.');
client('aiAudit','Client AI Audit','Review a reconciliation and explanatory findings for this client.','Use this to investigate discrepancies. Use Audit Record for the deterministic record-by-record change history.','An audit reads balances and creates review evidence; it does not issue invoices, record cash or change the amount owed. Findings need review against the underlying records.',reports,'Correct source records through their supported workflows. An audit finding does not unlock a sent invoice or authorize a non-admin adjustment.');
client('auditRecord','Audit Record','Read who changed this client’s records, when and why, and create an immutable evidence document.','Use the timeline and verification tools to trace an entry. Choose a readable client record or the full evidence record when printing.','The append-only history links financial changes without posting additional debt, cash or revenue. Printed records preserve the evidence available when created.', 'Admins and super admins can view, verify and print the Audit Record.', 'History and printed evidence cannot be edited or deleted. Correct the underlying record through an authorized new action; the original change remains visible.');
client('edit','Edit client','Update contact and client configuration details.','Use this for names, addresses and other client settings. Use Recurring plans for versioned recurring fees and dates.','Contact edits do not move money between businesses or rewrite issued letterheads. Changes are audited; recurring settings affect eligible future billing.',operators,'Correct eligible details and save once. Issued financial records remain locked, and removing a client with financial history is guarded.');

function helpForPath(pathname) {
  const parts = pathname.split(/[?#]/)[0].replace(/\/$/, '').split('/');
  const routes = Object.keys(pageHelp).sort((a,b) => b.split('/').length-a.split('/').length || Number(a.includes('/:'))-Number(b.includes('/:')) || b.length-a.length);
  const key = routes.find(route => route.split('/').every((part,i) => part.startsWith(':') ? Boolean(parts[i]) : part===parts[i]));
  return key ? pageHelp[key] : null;
}
function renderHelpMarkdown() {
  return '# About DS2 pages\n\nGenerated from `DS2_Frontend/src/help/pageHelp.js`. Run `node scripts/docs/generate-page-help.js` from DS2_Backend; `--check` verifies this file. The shared information button uses this same content.\n\n' + Object.entries(pageHelp).map(([route, help]) => `## ${help.title}\n\nRoute: \`${route}\`\n\n${help.bullets.map(text=>'- '+text).join('\n')}\n`).join('\n');
}
module.exports = { pageHelp, helpForPath, renderHelpMarkdown };
