import CustomerPicker from '../../Components/Lookups/CustomerPicker';
import React,{useContext,useEffect,useRef,useState} from 'react';
import {Alert,Button,Stack,TextField,Typography} from '@mui/material';
import {context} from '../../App';
import EntityPicker from '../../Components/BillingEntities/EntityPicker';
import {creditCall,receiptError} from '../../Services/ApiCalls/ReceiptCalls';
export default function ReceiptCreditTransfer({customerData}){
 const {loggedInUser}=useContext(context),admin=['admin','super admin'].includes((loggedInUser.accessLevel || '').toLowerCase());
 const [form,setForm]=useState({customerId:'',sourceEntityId:null,destinationEntityId:null,creditId:'',amount:'',reason:''}),[state,setState]=useState(null),[history,setHistory]=useState([]),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const key=useRef(null),flight=useRef(false);
 const historyLoad=()=>creditCall('/transfers').then(r=>setHistory(r.transfers)).catch(e=>setError(receiptError(e)));
 useEffect(()=>{historyLoad();},[]);
 useEffect(()=>{let live=true;setState(null);if(form.customerId && form.sourceEntityId)creditCall(`?customerId=${form.customerId}&entityId=${form.sourceEntityId}`).then(r=>{if(live)setState(r);}).catch(e=>{if(live)setError(receiptError(e));});return()=>{live=false;};},[form.customerId,form.sourceEntityId,message]);
 const change=(k,value)=>{key.current=null;setForm(f=>({...f,[k]:value,...(['customerId','sourceEntityId'].includes(k)?{creditId:''}:{})}));};
 const credit=state?.credits.find(c=>String(c.credit_id)===form.creditId),amount=Math.round(Number(form.amount)*100);
 const valid=credit && /^\d+(\.\d{1,2})?$/.test(form.amount) && amount>0 && amount<=credit.availableCents && form.reason.trim() && form.destinationEntityId && form.destinationEntityId!==form.sourceEntityId;
 const submit=async()=>{if(flight.current || !valid)return;flight.current=true;setBusy(true);setError('');key.current ||= window.crypto.randomUUID();try{const r=await creditCall('/transfers','post',{...form,ledgerFingerprint:state.ledgerFingerprint},key.current);setMessage(r.message);setForm(f=>({...f,creditId:'',amount:'',reason:''}));key.current=null;await historyLoad();}catch(e){setError(receiptError(e));}finally{flight.current=false;setBusy(false);}};
 return <Stack spacing={2}><Typography variant='h6'>Transfer unused receipt credit</Typography>{error && <Alert severity='error'>{error}<Button onClick={()=>{setMessage(String(Date.now()));key.current=null;}}>Refresh available receipt credit</Button></Alert>}{message && !/^\d+$/.test(message) && <Alert severity='success'>{message}</Alert>}{admin && <><CustomerPicker native customerData={customerData}   InputLabelProps={{shrink:true}} label='Receipt credit client' value={form.customerId} onChange={value=>change('customerId',value)} /><EntityPicker label='Receipt credit from business' all value={form.sourceEntityId} onChange={v=>change('sourceEntityId',v)}/><EntityPicker label='Receipt credit to business' all value={form.destinationEntityId} onChange={v=>change('destinationEntityId',v)}/><TextField select SelectProps={{native:true}} InputLabelProps={{shrink:true}} label='Unused receipt credit' value={form.creditId} onChange={e=>change('creditId',e.target.value)}><option value=''>Choose credit</option>{state?.credits.filter(c=>c.kind==='held_receipt' && c.availableCents>0).map(c=><option key={c.credit_id} value={c.credit_id}>Receipt #{c.origin_receipt_id} · ${(c.availableCents/100).toFixed(2)} available</option>)}</TextField><TextField label='Receipt credit transfer amount' value={form.amount} onChange={e=>change('amount',e.target.value)}/><TextField label='Receipt credit transfer reason' value={form.reason} onChange={e=>change('reason',e.target.value)}/>{credit && amount>credit.availableCents && <Alert severity='info'>Amount exceeds available receipt credit.</Alert>}<Button disabled={busy || !valid} onClick={submit}>Transfer receipt credit</Button></>}<Typography variant='h6'>Receipt credit transfer history</Typography>{history.length?history.map(t=><Typography key={t.event_id}>{t.client_name} · {t.source_name} → {t.destination_name} · ${Number(t.amount).toFixed(2)} · {t.reason} · Receipt #{t.origin_receipt_id}</Typography>):<Typography>No receipt credit transfers.</Typography>}</Stack>;
}
