import React,{useCallback,useContext,useEffect,useRef,useState} from 'react';
import {useParams} from 'react-router-dom';
import {Alert,Button,Stack,TextField,Typography} from '@mui/material';
import {context} from '../../App';
import {receiptCall,receiptError} from '../../Services/ApiCalls/ReceiptCalls';
export default function ReceiptDetailPage(){
 const {receiptId}=useParams(),{loggedInUser}=useContext(context),admin=['admin','super admin'].includes((loggedInUser.accessLevel || '').toLowerCase());
 const [data,setData]=useState(null),[error,setError]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[applicationId,setApplicationId]=useState(''),[obligationId,setObligationId]=useState(''),[open,setOpen]=useState([]);const flight=useRef(false),key=useRef(null),revision=useRef(0);
 const load=useCallback(async()=>{
  const request=++revision.current;setData(null);setOpen([]);setError('');setApplicationId('');setObligationId('');
  try{const d=await receiptCall(`/receipts/${receiptId}`);if(request!==revision.current)return;
   const o=await receiptCall(`/open-obligations?customerId=${d.receipt.customer_id}&entityId=${d.receipt.billing_entity_id}`);
   if(request!==revision.current)return;setOpen(o.obligations);setData(d);
  }catch(e){if(request===revision.current)setError(receiptError(e));}
 },[receiptId]);
 useEffect(()=>{setReason('');setMessage('');key.current=null;load();return()=>{revision.current+=1;};},[load]);
 const submit=async(path,body)=>{if(flight.current)return;flight.current=true;setBusy(true);setError('');key.current ||= window.crypto.randomUUID();try{const r=await receiptCall(`/receipts/${receiptId}/${path}`,'post',{...body,reason,ledgerFingerprint:data.ledgerFingerprint},key.current);setMessage(r.message);key.current=null;await load();}catch(e){setError(receiptError(e));}finally{flight.current=false;setBusy(false);}};
 const flag=data?.events.some(e=>e.kind==='exception_flagged'),reversed=data?.events.some(e=>e.kind==='reversed'),resolved=data?.events.some(e=>e.kind.startsWith('resolved_'));
 const applications=data?.applications.filter(a=>a.direction===1 && !a.finalized && !a.credit_id && !data.applications.some(r=>r.reversal_of===a.application_id)) || [];
 return <Stack spacing={2} sx={{p:3,maxWidth:1050}}><Typography variant='h4'>Receipt #{receiptId}</Typography>{error && <Alert severity='error'>{error}<Button onClick={load}>Refresh receipt</Button></Alert>}{message && <Alert severity='success'>{message}</Alert>}{!data && !error && <Typography role='status'>Loading receipt and open invoices…</Typography>}{data && <><Typography>Received ${Number(data.receipt.amount).toFixed(2)} · {data.receipt.method} · {data.receipt.reference} · {String(data.receipt.receipt_date).slice(0,10)}</Typography><Typography variant='h6'>Applications</Typography>{data.applications.map(a=><Typography key={a.application_id} title={`Application ID: ${a.application_id}; invoice balance ID: ${a.obligation_id}`}>{a.invoice_number || 'Historical opening balance'} · ${Number(a.amount).toFixed(2)} {a.direction===-1?'reversed':''}</Typography>)}{data.receipt.source_kind!=='manual'?<Alert severity='info'>Historical payment record. Use the linked legacy payment or retainer workflow for corrections.</Alert>:!admin?<Alert severity='info'>Only admins can correct applications or apply a bounced-check exception.</Alert>:<>
  <TextField label='Reason for correction' multiline value={reason} onChange={e=>{key.current=null;setReason(e.target.value);}} disabled={busy}/>
  {!flag && !reversed && <><Typography variant='h6'>Correct one application</Typography><Typography>Before finalization, move an application to the correct invoice without changing the received amount. Finalized applications are locked.</Typography><TextField select SelectProps={{native:true}} InputLabelProps={{shrink:true}} label='Application to correct' value={applicationId} onChange={e=>{key.current=null;setApplicationId(e.target.value);}}><option value=''>Choose application</option>{applications.map(a=><option key={a.application_id} value={a.application_id}>{a.invoice_number || 'Historical opening balance'} · ${Number(a.amount).toFixed(2)}</option>)}</TextField><TextField select SelectProps={{native:true}} InputLabelProps={{shrink:true}} label='Correct open invoice' value={obligationId} onChange={e=>{key.current=null;setObligationId(e.target.value);}}><option value=''>Choose invoice</option>{open.map(o=><option key={o.obligation_id} value={o.obligation_id}>{o.invoice_number} · ${(o.openCents/100).toFixed(2)}</option>)}</TextField><Button disabled={busy || !reason.trim() || !applicationId || !obligationId} onClick={()=>submit(`applications/${applicationId}/correct`,{obligationId,amount:applications.find(a=>String(a.application_id)===applicationId)?.amount})}>Correct application</Button><Button color='error' disabled={busy || !reason.trim() || data.applications.some(a=>a.finalized)} onClick={()=>submit('cancellations',{})}>Cancel unissued receipt entered in error</Button>{data.receipt.method==='check' && <Button disabled={busy || !reason.trim()} onClick={()=>submit('exceptions',{condition:'bounced_check'})}>Flag complete receipt as bounced</Button>}</>}
  {flag && !reversed && <><Alert severity='warning'>Reversing this receipt restores every invoice application and cancels its remaining credit.</Alert><Button disabled={busy || !reason.trim()} color='error' variant='contained' onClick={()=>submit('reversals',{})}>Reverse complete receipt</Button></>}
  {reversed && flag && !resolved && <><Alert severity='info'>The whole receipt is reversed. Resolve its statement correction.</Alert><Button disabled={busy || !reason.trim()} onClick={()=>submit('resolve',{action:'roll_forward'})}>Roll correction into next statement</Button><Button disabled={busy || !reason.trim()} onClick={()=>submit('resolve',{action:'revision'})}>Create statement revisions</Button></>}
 </>}<Typography variant='h6'>Remaining receipt credit</Typography>{data.credits?.length?data.credits.map(c=><Typography key={c.credit_id}>{c.business || 'Business name unavailable'} · ${(Number(c.availableCents || 0)/100).toFixed(2)} available</Typography>):<Typography>No held credit.</Typography>}<Typography variant='h6'>Receipt history</Typography>{data.events.map(e=><Typography key={e.event_id}>{e.kind.replaceAll('_',' ')} · {e.reason}</Typography>)}</>}</Stack>;
}
