import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {MemoryRouter,Link,Route,Routes} from 'react-router-dom';
import {context} from '../../../App';
import InvoiceRoutes from './InvoiceSubRoutes';
import {fetchCustomerInvoiceInformation} from '../../../Services/ApiCalls/FetchCalls';
jest.mock('../../../App',()=>({context:require('react').createContext({})}));
jest.mock('../../../Services/ApiCalls/FetchCalls',()=>({fetchCustomerInvoiceInformation:jest.fn()}));
jest.mock('../../useRowData',()=>({useRowData:()=>({rowData:{customer_invoice_id:1}})}));
jest.mock('../../../Components/PageNavigationHeader/PageNavigationHeader',()=>()=>null);
jest.mock('../../../Pages/Invoices/InvoiceDetails/InvoiceDetails',()=>({invoiceData,postStatus,setPostStatus})=><div>Invoice {invoiceData.invoiceDetails?.customer_invoice_id}<button onClick={()=>setPostStatus({status:200,message:'Downloaded'})}>Download</button><button onClick={()=>setPostStatus({status:500,message:'Download unavailable'})}>Failed download</button>{postStatus?.message}</div>);
jest.mock('../../../Pages/Invoices/InvoiceDetails/InvoiceTransactions',()=>()=>null);
jest.mock('../../../Pages/Invoices/InvoiceDetails/InvoicePayments',()=>()=>null);
jest.mock('../../../Pages/Invoices/InvoiceDetails/InvoiceWriteOffs',()=>()=>null);
jest.mock('../../../Pages/Invoices/InvoiceDetails/InvoiceOutstandingInvoices',()=>()=>null);
jest.mock('../../../Pages/Invoices/InvoiceDetails/InvoiceRetainers',()=>()=>null);
const mount=()=>render(<MemoryRouter initialEntries={['/billing/invoices/1/work']}><context.Provider value={{loggedInUser:{accountID:9001,userID:90013}}}><Link to='/billing/invoices/2/work'>Replacement</Link><Link to='/billing/invoices/1/work'>Original</Link><Link to='/billing/invoices/2/payments'>Payments tab</Link><Routes><Route path='/billing/invoices/:invoiceId/*' element={<InvoiceRoutes/>}/></Routes></context.Provider></MemoryRouter>);
const result=id=>({status:200,invoiceDetails:{customer_invoice_id:id}});
beforeEach(()=>{jest.clearAllMocks();fetchCustomerInvoiceInformation.mockImplementation((a,u,id)=>Promise.resolve(result(id)));});
test('replacement and original links load their own frozen documents without a full remount',async()=>{mount();await screen.findByText('Invoice 1');fireEvent.click(screen.getByText('Replacement'));await screen.findByText('Invoice 2');fireEvent.click(screen.getByText('Payments tab'));await screen.findByText('Invoice 2');fireEvent.click(screen.getByText('Original'));await screen.findByText('Invoice 1');expect(screen.queryByText('Invoice 2')).not.toBeInTheDocument();});
test('late original fetch cannot replace the newly selected invoice',async()=>{let finish;fetchCustomerInvoiceInformation.mockImplementation((a,u,id)=>id===1?new Promise(r=>{finish=r;}):Promise.resolve(result(id)));mount();fireEvent.click(screen.getByText('Replacement'));await screen.findByText('Invoice 2');finish(result(1));await waitFor(()=>expect(screen.getByText('Invoice 2')).toBeVisible());expect(screen.queryByText('Invoice 1')).not.toBeInTheDocument();});
test('load failure offers retry and never renders a wrong invoice',async()=>{fetchCustomerInvoiceInformation.mockResolvedValueOnce(result(99)).mockResolvedValue(result(1));mount();await screen.findByRole('alert');expect(screen.queryByText('Invoice 99')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Try again'}));await screen.findByText('Invoice 1');});
test('download success and failure leave the loaded invoice available',async()=>{mount();await screen.findByText('Invoice 1');fireEvent.click(screen.getByRole('button',{name:'Download',exact:true}));expect(screen.getByText(/Invoice 1/)).toBeVisible();expect(screen.getByText(/Downloaded/)).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'Failed download'}));expect(screen.getByText(/Invoice 1/)).toBeVisible();expect(screen.getByText(/Download unavailable/)).toBeVisible();expect(fetchCustomerInvoiceInformation).toHaveBeenCalledTimes(1);});
