import ActorName from '../../Components/Workspace/ActorName';
import React,{useContext,useEffect,useRef,useState} from 'react';
import {Alert,Button,Stack,TextField,Typography,Table,TableHead,TableBody,TableRow,TableCell,Pagination,TableContainer} from '@mui/material';
import {Link} from 'react-router-dom';
import {context} from '../../App';
import EntityPicker from '../../Components/BillingEntities/EntityPicker';
import {isAdjustmentAdmin} from '../../Components/AdminAdjustment';
import {correctionCall,correctionError,correctionPdf} from '../../Services/ApiCalls/CorrectionCalls';
export default function CorrectionRegister({kind='credit-memos'}){
 const {loggedInUser}=useContext(context),admin=isAdjustmentAdmin(loggedInUser.accessLevel),memo=kind==='credit-memos';
 const [data,setData]=useState({records:[],totalCount:0}),[entity,setEntity]=useState(null),[page,setPage]=useState(1),[selected,setSelected]=useState(null),[reason,setReason]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reload,setReload]=useState(0),[loading,setLoading]=useState(true);
 const flight=useRef(false),key=useRef(null);
 useEffect(()=>{let live=true;setLoading(true);setError('');setData({records:[],totalCount:0});correctionCall(`/${kind}?page=${page}&limit=25${entity?`&entityId=${entity}`:''}`).then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(correctionError(e));}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[kind,entity,page,reload]);
 const downloadReversal=async r=>{try{await correctionPdf(`/credit-memos/reversals/${r.reversal_id}/pdf`);}catch(e){setError(correctionError(e));}};
 const download=async r=>{try{await correctionPdf(`/${kind}/${r.memo_id || r.refund_id}/pdf`);}catch(e){setError(correctionError(e));}};
 const select=async r=>{if(flight.current)return;flight.current=true;setBusy(true);setSelected(null);setError('');setMessage('');try{const info=await correctionCall(`/credit-memos/${r.memo_id}`);if(info.reversals.length){setMessage('This memo is already reversed.');return;}const state=await correctionCall(`/invoices/${r.original_invoice_id}/corrections`);setSelected({...r,ledgerFingerprint:state.ledgerFingerprint});setReason('');key.current=null;}catch(e){setError(correctionError(e));}finally{flight.current=false;setBusy(false);}};
 const reverse=async()=>{if(flight.current || !reason.trim())return;flight.current=true;setBusy(true);setError('');key.current ||= window.crypto.randomUUID();try{const r=await correctionCall(`/credit-memos/${selected.memo_id}/reversals`,'post',{entityId:selected.billing_entity_id,reason,ledgerFingerprint:selected.ledgerFingerprint},key.current);setMessage(r.message);setSelected(null);setReload(n=>n+1);}catch(e){setError(correctionError(e));}finally{flight.current=false;setBusy(false);}};
 return <Stack spacing={2} sx={{p:3}}><Typography variant='h4'>{memo?'Credit memos':'Money returned to clients'}</Typography><Button component={Link} to={memo?'/billing/invoices':'/payments/credits'}>{memo?'Open an invoice to issue a credit memo':'Open client credits to record a refund'}</Button>{error && <Alert severity='error'>{error}<Button onClick={()=>setReload(n=>n+1)}>Try again</Button></Alert>}{message && <Alert severity='success'>{message}</Alert>}{!admin && <Alert severity='info'>Only admins may apply corrections. You can read and download these records.</Alert>}<EntityPicker disabled={busy} all value={entity} onChange={v=>{setEntity(v);setPage(1);setSelected(null);}}/>
 {loading && <Typography role='status'>Loading records…</Typography>}{!loading && !error && !data.records.length && <Alert severity='info'>{memo?'No credit memos match this business. Open a finalized invoice to issue one.':'No refunds match this business. Open client credits to record money returned.'}</Alert>}
 <TableContainer><Table size='small' sx={{minWidth:780,'& td':{verticalAlign:'top'},'& button':{whiteSpace:'nowrap'}}}><TableHead><TableRow>{['Document','Status','Client / business','Date / amount','Reason','Actions'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{data.records.map(r=><TableRow key={r.memo_id || r.refund_id}><TableCell sx={{whiteSpace:'nowrap'}}>{r.number || `Refund #${r.refund_id}`}</TableCell><TableCell>{r.reversal_id?'Reversed':'Issued'}</TableCell><TableCell>{r.display_name} · {r.billing_entity_name}</TableCell><TableCell><Typography variant='body2' sx={{whiteSpace:'nowrap'}}>{String(r.effective_date).slice(0,10)}</Typography><Typography variant='body2' sx={{whiteSpace:'nowrap'}}>${Number(r.amount).toFixed(2)}</Typography></TableCell><TableCell>{r.reason}<Typography variant='caption' display='block'><ActorName id={r.actor_id} name={r.actor_name}/></Typography></TableCell><TableCell><Button onClick={()=>download(r)}>Download {r.number || `refund #${r.refund_id}`}</Button>{memo && r.reversal_id && <Button onClick={()=>downloadReversal(r)}>Download reversal of {r.number}</Button>}{memo && admin && !r.reversal_id && <Button disabled={busy} onClick={()=>select(r)}>Reverse memo {r.number}</Button>}</TableCell></TableRow>)}</TableBody></Table></TableContainer>
 <Pagination disabled={loading || busy} page={page} count={Math.max(1,Math.ceil(data.totalCount/25))} onChange={(_,v)=>setPage(v)}/>
 {selected && admin && <Alert severity='warning'>Reverse {selected.number} for ${selected.amount}. This creates a locked compensating document and preserves the memo.<TextField label='Memo reversal reason' value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);key.current=null;}}/><Button disabled={busy || !reason.trim()} onClick={reverse}>Confirm memo reversal</Button><Button disabled={busy} onClick={()=>setSelected(null)}>Cancel memo reversal</Button></Alert>}
 </Stack>;
}
