import CustomerPicker from '../../Components/Lookups/CustomerPicker';
import React,{useContext,useEffect,useRef,useState} from 'react';
import {Alert,Button,Stack,TextField,Typography,Table,TableBody,TableCell,TableHead,TableRow} from '@mui/material';
import {Link,useSearchParams} from 'react-router-dom';
import {context} from '../../App';
import EntityPicker from '../../Components/BillingEntities/EntityPicker';
import {isAdjustmentAdmin} from '../../Components/AdminAdjustment';
import {correctionCall,correctionError} from '../../Services/ApiCalls/CorrectionCalls';
export default function CreditsPage({customerData}){
 const [searchParams]=useSearchParams();
 const {loggedInUser}=useContext(context),admin=isAdjustmentAdmin(loggedInUser.accessLevel);
 const [client,setClient]=useState(searchParams.get('customerId') || ''),[entity,setEntity]=useState(searchParams.get('entityId') || null),[data,setData]=useState(null),[credit,setCredit]=useState(null),[form,setForm]=useState({amount:'',date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Phoenix',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),method:'check',reference:'',reason:''}),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[refresh,setRefresh]=useState(0);
 const key=useRef(null),flight=useRef(false);
 useEffect(()=>{let live=true;setData(null);setCredit(null);setReview(false);key.current=null;if(client && entity)correctionCall(`/credits?customerId=${client}&entityId=${entity}`).then(r=>{if(live)setData(r);}).catch(e=>{if(live)setError(correctionError(e));});return()=>{live=false;};},[client,entity,refresh]);
 const change=(k,value)=>{setForm(f=>({...f,[k]:value}));setReview(false);key.current=null;};
 const valid=credit && /^\d+(\.\d{1,2})?$/.test(form.amount) && Number(form.amount)>0 && Math.round(Number(form.amount)*100)<=credit.availableCents && form.reason.trim() && form.date && (form.method==='cash' || form.reference.trim());
 const submit=async()=>{if(flight.current || !valid || !admin)return;flight.current=true;setBusy(true);setError('');key.current ||= window.crypto.randomUUID();try{const r=await correctionCall(`/credits/${credit.credit_id}/refunds`,'post',{...form,entityId:entity,ledgerFingerprint:data.ledgerFingerprint},key.current);setMessage(`${r.message} Remaining credit $${r.remainingCredit}.`);setForm(f=>({...f,amount:'',reason:'',reference:''}));setRefresh(n=>n+1);}catch(e){setError(correctionError(e));}finally{flight.current=false;setBusy(false);}};
 return <Stack spacing={2} sx={{p:3}}><Typography variant='h4'>Client credits and refunds</Typography><Stack direction='row' spacing={2}><Button component={Link} to='/payments/refunds'>Refund history</Button><Button component={Link} to='/payments/transfers'>Credit transfers</Button></Stack>
 {error && <Alert severity='error'>{error}<Button disabled={busy} onClick={()=>{setRefresh(n=>n+1);setError('');}}>Refresh available credit</Button></Alert>}{message && <Alert severity='success'>{message}</Alert>}{!admin && <Alert severity='info'>Only admins may refund client credit. Records remain available.</Alert>}
 <CustomerPicker native customerData={customerData}   InputLabelProps={{shrink:true}} label='Credit client' value={client} disabled={busy} onChange={value=>{setClient(value);setMessage('');}} /><EntityPicker label='Credit business' disabled={busy} all value={entity} onChange={v=>{if(!busy)setEntity(v);}}/>
 <Table><TableHead><TableRow>{['Credit','Source','Available','Action'].map(x=><TableCell key={x}>{x}</TableCell>)}</TableRow></TableHead><TableBody>{data?.credits.map(c=><TableRow key={c.credit_id}><TableCell>Credit #{c.credit_id}</TableCell><TableCell>{c.kind==='held_receipt'?`Receipt #${c.origin_receipt_id}`:c.derivation_label || 'Issued statement credit'}</TableCell><TableCell>${(c.availableCents/100).toFixed(2)}</TableCell><TableCell>{admin && c.availableCents>0 && <Button disabled={busy} onClick={()=>{setCredit(c);setReview(false);key.current=null;}}>Refund credit #{c.credit_id}</Button>}</TableCell></TableRow>)}</TableBody></Table>
 {admin && credit && <Stack spacing={2}><Typography variant='h6'>Refund credit #{credit.credit_id}</Typography><TextField label='Refund amount' value={form.amount} disabled={busy} onChange={e=>change('amount',e.target.value)}/>{Math.round(Number(form.amount)*100)>credit.availableCents && <Alert severity='error'>Refund exceeds available credit.</Alert>}<TextField label='Refund date' type='date' InputLabelProps={{shrink:true}} value={form.date} disabled={busy} onChange={e=>change('date',e.target.value)}/><TextField select SelectProps={{native:true}} label='Refund method' value={form.method} disabled={busy} onChange={e=>change('method',e.target.value)}><option value='check'>Check</option><option value='cash'>Cash</option><option value='other'>Other</option></TextField><TextField label='Refund reference' value={form.reference} disabled={busy} onChange={e=>change('reference',e.target.value)}/><TextField label='Refund reason' required multiline inputProps={{maxLength:2000}} value={form.reason} disabled={busy} onChange={e=>change('reason',e.target.value)}/><Button disabled={!valid || busy} onClick={()=>setReview(true)}>Review refund</Button>{review && <Alert severity='warning'>Record ${Number(form.amount).toFixed(2)} as money returned. Available after: ${(credit.availableCents/100-Number(form.amount)).toFixed(2)}. {credit.kind==='held_receipt'?'Invoice debt stays unchanged.':'Issued credit moves toward zero.'}<Button disabled={busy} onClick={submit}>Record refund</Button></Alert>}</Stack>}
 </Stack>;
}
